---
openapi: 3.0.0
info:
  title: Beneficiary Service - Inquiry
  description: Beneficiary service consists of operations used to manage the beneficial party associated with an account. Beneficial party nominated, can claim the proceeds of the bank account post the demise of account holder.
  version: 11.0.0
servers:
- url: /
paths:
  /beneficiaries/secured:
    post:
      tags:
      - Get Beneficiary
      summary: Get Beneficiary.
      description: "Retrieves information of beneficiary associated with an account.  <br><br> For more information about the Accountholder domain, <a href=\"../docs/?path=docs/fintechs/accountholder.md\" title=\"Click to open\">click here.</a> <br><br> <b>Relates to:</b>\n  <ul> \n    <li><a href=\"../docs/?path=docs/banks-and-CU/deposits.md\" title=\"Click to open\">Deposits</a></li>\n    <li><a href=\"../docs/?path=docs/banks-and-CU/bank-servicing.md\" title=\"Click to open\">Bank Servicing</a></li>\n  </ul> \n  \n  <br>\n  \n   <blockquote style=\"border-left: 0.375em solid #40a9ff; background-color: #e6f7ff; border-radius: 3px; padding: 1em;\" > To view provider specific implementation notes and applicable fields, <a target=\"_blank\" title=\"Click to open in a new tab\" href=\"../docs/?path=docs/implementation-notes/Accountholder/BenificiaryInq-ImplNotes.md\">click here</a>.</blockquote>"
      parameters:
      - name: EFXHeader
        in: header
        description: EFX Header is a common and required component for all API calls, it contains authentication and client-related parameters. Please note that the header parameters should be sent as a JSON object under the EFXHeader parameter. To view the list of header parameters, <a href="../docs?path=docs/api-ref-EFX-header.md" title="Click to open"> click here.</a>
        required: true
        schema:
          $ref: '#/components/schemas/EFXHeader'
      requestBody:
        description: Beneficiary info
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BeneficiaryInqRqType'
            examples:
              Sample DNA:
                $ref: '#/components/examples/BeneficiaryInqRq-DNA'
              Sample Premier:
                $ref: '#/components/examples/BeneficiaryInqRq-PRM'
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeneficiaryInqRsType'
              examples:
                Sample DNA:
                  $ref: '#/components/examples/BeneficiaryInqRs-DNA'
                Sample Premier:
                  $ref: '#/components/examples/BeneficiaryInqRs-PRM'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeneficiaryInqRsType'
              examples:
                "401":
                  $ref: '#/components/examples/401-Premier'
        "422":
          description: Un-processable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeneficiaryInqRsType'
              examples:
                "422":
                  $ref: '#/components/examples/422-Premier'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeneficiaryInqRsType'
              examples:
                "500":
                  $ref: '#/components/examples/500-Premier'
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeneficiaryInqRsType'
              examples:
                "503":
                  $ref: '#/components/examples/503-Premier'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeneficiaryInqRsType'
      deprecated: false
      x-group-name: Beneficiary Service
      x-proxy-name: Get Beneficiary
      x-child-product-name: Accountholder
components:
  schemas:
    AcctIdentTypeType:
      title: AcctIdentTypeType
      type: string
      enum:
      - AcctNum
      - PORT
      - AccessId
      - PartyId
      - AliasAcct
      - AcctTypeCode
      - CLOC
    AcctTypeType:
      title: AcctTypeType
      type: string
      enum:
      - CCA
      - RRA
      - LEAS
      - CDA
      - MLN
      - CLA
      - CRD
      - DDA
      - EQU
      - GLA
      - ILA
      - AdultCashISA
      - IRA
      - RET
      - EXT
      - JuniorCashISA
      - LIP
      - LOAN
      - LOC
      - CLOC
      - MLA
      - PBA
      - PORT
      - SDA
      - SDB
      - MMA
      - DDL
    AddrFormatTypeType:
      title: AddrFormatTypeType
      type: string
      description: Type of address format
      example: Parsed
      enum:
      - Label
      - Parsed
    AddrTypeType:
      title: AddrTypeType
      type: string
      description: "Type of the address. <br> Valid value is: \n  - Primary"
      example: Primary
      enum:
      - Primary
      - PrimaryPending
      - Secondary
      - Seasonal
      - Previous
      - Physical
    AddrUseType:
      title: AddrUseType
      type: string
      enum:
      - Business
      - Home
      - Personal
      - Government
      - LegalTitle
      - StmtPrimary
      - StmtAddtl
      - Inquiry
      - Mailing
      - Check
      - Dividend
      - Physical
      - Tax
      - Stmt
      - Beneficiary
      - MultipleMailer
      - Miscellaneous
      - Tickler
      - Indirect
      - Closed
      - 1098Tax
      - 1099ATax
      - 1099BTax
      - 1099Tax
      - 1099DIVTax
      - 1099INTTax
      - 1099MISCTax
      - 1099OIDTax
      - 1099RTax
      - 1099STax
      - 5498Tax
      - TaxBNotice
      - 1099CTax
      - 1099ETax
      - 1042STax
      - NoteCollateral
      - NoteCosigner
      - NoteEscrow
      - NoteTaxEscrow
      - NoteInsuranceEscrow
      - LineCollateral
      - FinancialPropertyStmt
      - LineCosigner
      - LineCommitment
      - PaidNote
      - Property
      - Appraiser
      - Broker
      - Builder
      - InsuranceAgency
      - InsuranceCompany
      - Landlord
      - LienHolder
      - CollateralLocation
      - PolicyHolder
      - Seller
      - Trustee
      - Issuer
    AdjDaysBasisType:
      title: AdjDaysBasisType
      type: string
      enum:
      - DueDt
      - EndOfMonth
      - StmtDt
    ApartmentNumTypeType:
      title: ApartmentNumTypeType
      type: string
      enum:
      - APT
      - BLDG
      - DEPT
      - FL
      - HNGR
      - KEY
      - LOT
      - OFC
      - PH
      - PIER
      - RM
      - SLIP
      - SPC
      - STOP
      - STE
      - TRLR
      - UNIT
    BeneficiaryLevelType:
      title: BeneficiaryLevelType
      type: string
      enum:
      - PrimaryDesignated
      - PrimaryNonDesignated
      - Secondary
      - Contingent
    BeneficiaryStatusCodeType:
      title: BeneficiaryStatusCodeType
      type: string
      description: |-
        Status code of a beneficiary. <br> Some of the valid values are:
          - Valid
          - Deleted
      enum:
      - Valid
      - Deleted
    BeneficiaryTypeType:
      title: BeneficiaryTypeType
      type: string
      enum:
      - Aunt
      - Brother
      - Companion
      - Daugther
      - Father
      - Friend
      - Granddaugther
      - Grandfather
      - Grandson
      - Husband
      - Mother
      - Nephew
      - Niece
      - Sister
      - Son
      - Spouse
      - Uncle
      - Wife
      - Estate
      - Trust
      - CharitableOrg
    CardIdentTypeType:
      title: CardIdentTypeType
      type: string
      enum:
      - PORT
    CountryCodeSourceType:
      title: CountryCodeSourceType
      type: string
      enum:
      - FIPS-10
      - ISO3166-Numeric
      - ISO3166-Alpha-3
      - ISO3166-Alpha-2
      - IRS
      - SPCountryCode
    CurCodeTypeType:
      title: CurCodeTypeType
      type: string
      enum:
      - ISO4217-Alpha
      - ISO4217-Numeric
    DayOfMonthType:
      title: DayOfMonthType
      type: integer
      example: 1
      enum:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
    DayOfWeekType:
      title: DayOfWeekType
      type: string
      enum:
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
      - Sunday
    FIIdentTypeType:
      title: FIIdentTypeType
      type: string
      enum:
      - ABA
      - RoutingNum
    HandlingCodeOptionType:
      title: HandlingCodeOptionType
      type: string
      enum:
      - StatementsNoticesChecks
      - Statements
      - StatementsNotices
      - StatementsChecks
      - Notices
      - NoticesChecks
      - Checks
      - DoNotPrint
      - UsePortfolio
      - UseDefault
    MilitaryRegionType:
      title: MilitaryRegionType
      type: string
      enum:
      - APO AA
      - APO AE
      - APO AP
      - FPO AA
      - FPO AE
      - FPO AP
    OpenMethodType:
      title: OpenMethodType
      type: string
      enum:
      - InPerson
      - Internet
      - Mail
      - Phone
      - Mobile
      - Email
      - Fax
      - PostOffice
    PartyIdentTypeType:
      title: PartyIdentTypeType
      type: string
      enum:
      - TaxIdent
      - IBId
      - Name
      - MemberNum
      - OrgNum
      - PersonNum
    PhoneTypeType:
      title: PhoneTypeType
      type: string
      enum:
      - Fax-Foreign
      - Work-Foreign
      - Mobile-Foreign
      - EvePhone
      - DayPhone
      - EveFax
      - DayFax
      - Home
      - Work
      - Mobile
      - Fax
      - Pager
      - Modem
      - Other
    RecurTypeType:
      title: RecurTypeType
      type: string
      enum:
      - Daily
      - Maturity
      - InterestCycle
      - Monthly
      - BiMonthly
      - Once
      - SemiMonthly
      - TwiceMonthly
      - Weekly
      - BiWeekly
      - Yearly
      - SemiYearly
      - Cycle
      - None
      - PayOff
      - Anniversary
      - PmtRecalculation
      - Quarterly
      - CycleAndQuarterly
      - SvcChgCycle
    RelationshipRoleType:
      title: RelationshipRoleType
      type: string
      enum:
      - Officer
      - SecondOfficer
      - ThirdOfficer
      - FourthOfficer
      - ReferralOfficer
    SeverityType:
      title: SeverityType
      type: string
      description: Severity type of the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
      enum:
      - Error
      - Warning
      - Info
    SubjectRoleType:
      title: SubjectRoleType
      type: string
      enum:
      - Teller
      - Supervisor
    TaxIdentTypeType:
      title: TaxIdentTypeType
      type: string
      description: |-
        Type of tax identification. <br> Valid values are:
          - None
          - SSN
          - Foreign
          - ITIN
          - ATIN
          - EIN
      example: SSN
      enum:
      - None
      - SSN
      - EIN
      - Foreign
      - ITIN
      - ATIN
      - Other
    UnitType:
      title: UnitType
      type: string
      enum:
      - Seconds
      - Minutes
      - Hours
      - Days
      - Weeks
      - Months
      - Years
    AcctIdentType:
      title: AcctIdentType
      type: object
      properties:
        AcctIdentType:
          type: object
          description: 'Account Identification Type. Valid values include: AcctNum, AliasAcct, PORT, etc.'
        AcctIdentValue:
          maxLength: 36
          type: string
          description: Account Identification Value. Contains the value of the Account Identifier.
    BaseKeysType:
      title: BaseKeysType
      type: object
    SvcIdentType:
      title: SvcIdentType
      type: object
      properties:
        SvcProviderName:
          maxLength: 1024
          type: string
          description: Service Provider Name is a globally unique identifier for a service provider which indicates the location of the Service Provider that gave the error.
        SvcNbr:
          maxLength: 36
          type: string
          description: Service Number.
        SvcName:
          maxLength: 32
          type: string
          description: Service Name.
    CardIdentType:
      title: CardIdentType
      type: object
      properties:
        CardIdentType:
          type: object
          description: 'Card Identification Type. Valid values include: PORT.'
        CardIdentValue:
          maxLength: 36
          type: string
          description: Card Identification Value.
    CardKeysType:
      title: CardKeysType
      allOf:
      - $ref: '#/components/schemas/BaseKeysType'
      - type: object
        properties:
          SvcIdent:
            $ref: '#/components/schemas/SvcIdentType'
          ISOCode:
            maxLength: 80
            type: string
            description: ISO Card Code. Some systems like Precision instead of ISO Number they use a code to refer to the ISO Number of the card.
          CardNum:
            maxLength: 32
            type: string
            description: Card Number. This number does not include the ISO component of the card identification.
          CardId:
            maxLength: 36
            type: string
            description: Card Identifier. Uniquely identifies a card held at a financial institution (this is the card number as it appears on the card).
          CardSeqNum:
            maxLength: 3
            type: string
            description: Card Sequence Number. Typically refers to the member number (if applicable).
          CardIdent:
            $ref: '#/components/schemas/CardIdentType'
    CurCodeType:
      title: CurCodeType
      required:
      - CurCodeValue
      type: object
      properties:
        CurCodeType:
          $ref: '#/components/schemas/CurCodeTypeType'
        CurCodeTypeEnumDesc:
          maxLength: 80
          type: string
          description: Currency Code Type Enumeration Description.
        CurCodeValue:
          maxLength: 80
          type: string
          description: Currency Code Value. Indicates the Currency Code Value within the CurCodeType table specified.
    AcctKeysType:
      title: AcctKeysType
      description: Unique information to identify the account record
      allOf:
      - type: object
        properties:
          AcctId:
            maxLength: 36
            type: string
            description: Unique identification number of an account record
          AcctType:
            type: string
            description: |-
              Type of an account. <br> Valid values are:
                - DDA
                - SDA
                - CDA
              <br> For more information on account types, refer to the Account Types section in <a href="../docs?path=docs/api-glossary.md"  title="Click to open"> Glossary </a>.
    SubjectElementType:
      title: SubjectElementType
      type: object
      properties:
        Path:
          type: string
          description: Path of the element (in XPath absolute notation format) where the error occurred.  If the error occurred at the top-level element, then name of the element is returned in the response.
        ServerPath:
          maxLength: 256
          type: string
          description: Server Path is the Service Provider’s identification of the field in their schema, such as an XPath, field ID, or field name that is associated with the ServerStatusCode. If this element is set, it must be returned in the ServerPath element of the OvrdExceptionData aggregate if the exception is being overridden.
        Value:
          maxLength: 256
          type: string
          description: Human readable information of the EFX data value of the element to be overridden. This value should not be provided for the fields that cannot be represented as a string, for example, binary data.
      description: Information about the subject element
    AddrDefinedDataType:
      title: AddrDefinedDataType
      required:
      - DataIdent
      type: object
      properties:
        DataIdent:
          maxLength: 36
          type: string
          description: Data Identification. Identification of the client defined data item.
        Value:
          maxLength: 256
          type: string
          description: Value string representation of the EFX data value of the element in error. This field is intended to provide a human readable visual hint as to the value in error. It should not be provided for fields that cannot be represented as a string (i.e., binary data).
    OvrdElementType:
      title: OvrdElementType
      type: object
      description: Information about the elements that corresponds to the override exception code.
      allOf:
      - $ref: '#/components/schemas/SubjectElementType'
      - type: object
    OverrideExceptionType:
      title: OverrideExceptionType
      type: object
      properties:
        SubjectRole:
          type: string
          description: Role of the subject who is overriding the exception.
        SubjectIdent:
          maxLength: 36
          type: string
          description: Subject identification value to identify the subject who is overriding the exception.
        OvrdExceptionCode:
          maxLength: 40
          type: string
          description: Override exception code to be overridden. This can be the ServerStatusCode from the Message Status section.
        OvrdElement:
          $ref: '#/components/schemas/OvrdElementType'
    OvrdExceptionDataType:
      title: OvrdExceptionDataType
      type: object
      properties:
        OverrideException:
          type: array
          description: List of the exceptions that can be overridden.
          items:
            $ref: '#/components/schemas/OverrideExceptionType'
      description: Details of the exceptions that can be manually acknowledged by the client.
    PartyKeysType:
      title: PartyKeysType
      description: Unique information to identify a party record
      allOf:
      - type: object
        properties:
          PartyId:
            maxLength: 36
            type: string
            description: Unique identification number of a party record
    LocatorType:
      title: LocatorType
      type: object
    RelationshipMgrType:
      title: RelationshipMgrType
      required:
      - RelationshipMgrIdent
      type: object
      properties:
        RelationshipMgrIdent:
          maxLength: 36
          type: string
          description: Relationship Manager Identifier. Identifies officer/employee of financial institution.
        RelationshipMgrIdentEnumDesc:
          maxLength: 80
          type: string
          description: Relationship Manager Identifier Enumeration Description.
        RelationshipRole:
          $ref: '#/components/schemas/RelationshipRoleType'
        RelationshipRoleEnumDesc:
          maxLength: 80
          type: string
          description: Relationship Role Enumeration Description.
    LabelAddrType:
      title: LabelAddrType
      type: object
      properties:
        Addr1:
          maxLength: 64
          type: string
          description: Address Line 1.
        Addr2:
          maxLength: 64
          type: string
          description: Address Line 2.
        Addr3:
          maxLength: 64
          type: string
          description: Address Line 3.
        Addr4:
          maxLength: 64
          type: string
          description: Address Line 4.
        Addr5:
          maxLength: 64
          type: string
          description: Address Line 5.
        Addr6:
          maxLength: 64
          type: string
          description: Address Line 6.
    CountryCodeType:
      title: CountryCodeType
      required:
      - CountryCodeValue
      type: object
      properties:
        CountryCodeSource:
          type: string
          description: |-
            Standard format of country code <br> Valid value is:
              SPCountryCode
          example: SPCountryCode
        CountryCodeValue:
          maxLength: 80
          type: string
          description: Country code value as per the country code format set in the CountryCodeSource field
        CountryCodeValueEnumDesc:
          maxLength: 80
          type: string
          description: Enumeration description of country code value
      description: Country code details of the person associated with the beneficiary
    StartDayMonthType:
      title: StartDayMonthType
      type: object
      properties:
        DayOfMonth:
          $ref: '#/components/schemas/DayOfMonthType'
        Month:
          type: integer
          description: 'Month. Numeric value representing the month of recurrence. Valid values: integers between 1 and 12 inclusive.'
          format: int64
    DurationType:
      title: DurationType
      type: object
      properties:
        Count:
          type: integer
          description: Count. Sometimes specifies the duration of the time frame base on the units specified.
          format: int64
        Unit:
          type: object
          description: Unit.
        UnitEnumDesc:
          maxLength: 80
          type: string
          description: Unit Enumeration Description.
    RecurRuleType:
      title: RecurRuleType
      type: object
      properties:
        RecurType:
          type: object
          description: Recurrence Type. Indicates the pattern of recurrence.
        RecurTypeEnumDesc:
          maxLength: 80
          type: string
          description: Recurrence Type Enumeration Description.
        RecurInterval:
          type: integer
          description: 'Recurrence Interval. Number of units between occurrences. Should be an integer. If  ‘Daily’: Number of days between occurrences. If   ‘Weekly’: Number of weeks between occurrences. If   ''Monthly’: Number of months between occurrences. If   ‘Yearly’: Number of years between occurrences. If not provided, assume default value of 1, i.e. every day, every week, every month, or every year. If ''Cycle'' : Number of the designated cycle.'
          format: int64
        RecurInstance:
          type: integer
          description: Recurrent Instance. Numeric value representing the instance of the days(s) of the week of recurrence, i.e. Second Wednesday of the month, First Monday of the year. DayOfWeek must also be provided.
          format: int64
        DayOfWeek:
          $ref: '#/components/schemas/DayOfWeekType'
        DayOfMonth:
          $ref: '#/components/schemas/DayOfMonthType'
        SecondDayOfMonth:
          $ref: '#/components/schemas/DayOfMonthType'
        Month:
          type: integer
          description: 'Month. Numeric value representing the month of recurrence. Valid values: integers between 1 and 12 inclusive.'
          format: int64
        RecurStartDate:
          type: string
          description: Recurrence Start Date.
          format: date
        Occurrences:
          type: integer
          description: Occurrences.
          format: int64
        RecurEndDate:
          type: string
          description: Recurrence End Date.
          format: date
        LeadDays:
          type: integer
          description: Lead Days. Number of days prior to a specified date.
          format: int64
        AdjDays:
          type: integer
          description: Adjustment Days. Indicates the number of days to adjust a value (review a rate or perform interest accrual) after an event occurs (see AdjDaysBasis).
          format: int64
        AdjDaysBasis:
          type: object
          description: 'Adjustment Days Basis. Used in combination with Adjustment Days (AdjDays). It indicates a basis for an adjustment such as: Due Date (DueDt), Statement Date (StmtDt).'
    TimeFrameType:
      title: TimeFrameType
      type: object
      properties:
        StartDt:
          pattern: ^\[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?$
          type: string
          description: Start Date.
        StartDayMonth:
          $ref: '#/components/schemas/StartDayMonthType'
        EndDt:
          pattern: ^\[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?$
          type: string
          description: End Date.
        EndDayMonth:
          $ref: '#/components/schemas/StartDayMonthType'
        Duration:
          $ref: '#/components/schemas/DurationType'
        RecurRule:
          type: array
          description: Recurrence Rule.
          items:
            $ref: '#/components/schemas/RecurRuleType'
    PhoneNumType:
      title: PhoneNumType
      allOf:
      - $ref: '#/components/schemas/LocatorType'
      - required:
        - PhoneType
        type: object
        properties:
          PhoneType:
            type: object
            description: Phone Type.
          PhoneTypeEnumDesc:
            maxLength: 80
            type: string
            description: Phone Type Enumeration Description.
          PhoneIdent:
            type: integer
            description: Phone Identifier. Use when you have more than one occurrence of a phone type  (for example 5 Mobile phones). This element serializes the phones.
            format: int64
          Phone:
            type: string
            description: Phone.
          PhoneExchange:
            maxLength: 80
            type: string
            description: Phone Exchange.
          PreferredPhone:
            type: boolean
            description: Preferred Phone.
          Priority:
            maxLength: 10
            type: string
            description: Priority Code.
          DoNotContactInd:
            type: boolean
            description: Do Not Contact Indicator.
          PhoneDesc:
            maxLength: 30
            type: string
            description: Phone Description.
          CountryCode:
            $ref: '#/components/schemas/CountryCodeType'
          UpDt:
            pattern: ^\[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?$
            type: string
            description: Update Date.
    PostAddrType:
      title: PostAddrType
      description: Postal address details of the Beneficiary Party
      allOf:
      - required:
        - AddrType
        type: object
        properties:
          AddressIdent:
            maxLength: 36
            type: string
            description: 'Unique identifier of an address record. <br> <b>Note: </b>It is mandatory to provide details in this field if, existing address is to be added as a beneficiary address. '
          AddrFormatType:
            $ref: '#/components/schemas/AddrFormatTypeType'
          Addr1:
            maxLength: 64
            type: string
            description: Address line 1
          Addr2:
            maxLength: 64
            type: string
            description: Address line 2. <br>To enter Addr2, Addr1 field must be provided.
          City:
            maxLength: 32
            type: string
            description: Name of the city
          StateProv:
            maxLength: 80
            type: string
            description: State province name as per <a href="https://en.wikipedia.org/wiki/ISO_3166-2:US" title="Click to open" target="_blank" >ISO 3166-2:US codes</a>.
          PostalCode:
            maxLength: 11
            type: string
            description: Postal code or Zip code
          CountryCode:
            $ref: '#/components/schemas/CountryCodeType'
          AddrType:
            $ref: '#/components/schemas/AddrTypeType'
    BeneficiaryDataType:
      title: BeneficiaryDataType
      type: object
      properties:
        PartyKeys:
          $ref: '#/components/schemas/PartyKeysType'
        FullName:
          maxLength: 96
          type: string
          description: Full name of a person
        TaxIdentType:
          $ref: '#/components/schemas/TaxIdentTypeType'
        TaxIdent:
          maxLength: 12
          type: string
          description: Unique identifier of tax to identify the applicable tax on beneficiary
        BirthDt:
          type: string
          description: Date of birth of a person associated with the beneficiary
          format: date
          example: 1958-12-11
        PostAddr:
          $ref: '#/components/schemas/PostAddrType'
        BeneficiaryType:
          type: string
          description: |-
            Type of relationship between a beneficiary and an accountholder. <br> Some of the valid values are:
              - Aunt
              - Brother
              - Companion
              - Daughter
          example: Aunt
        BeneficiaryPercent:
          type: number
          description: Percentage of account balance that is conditionally allocated to the beneficiary
      description: Information of the Beneficiary Party
    BeneficiaryInfoType:
      title: BeneficiaryInfoType
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/AcctKeysType'
        BeneficiaryData:
          $ref: '#/components/schemas/BeneficiaryDataType'
      description: Beneficiary details of an account
    BeneficiaryKeysType:
      title: BeneficiaryKeysType
      description: Unique information to identify a beneficiary record
      allOf:
      - type: object
        properties:
          AcctKeys:
            $ref: '#/components/schemas/AcctKeysType'
          PartyKeys:
            $ref: '#/components/schemas/PartyKeysType'
          BeneficiaryIdent:
            maxLength: 36
            type: string
            description: Unique identifier of a beneficiary record
    BeneficiaryStatusType:
      title: BeneficiaryStatusType
      required:
      - BeneficiaryStatusCode
      type: object
      properties:
        BeneficiaryStatusCode:
          $ref: '#/components/schemas/BeneficiaryStatusCodeType'
        EffDt:
          pattern: ^\[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?$
          type: string
          description: 'Effective date and time when the beneficiary status is changed. <br> Format: yyyy-MM-ddTHH:mm:ss.SSS'
          example: 2021-01-31T23:59:59.999
      description: Details of the recent updates made to a beneficiary
    BeneficiaryStatusRecType:
      title: BeneficiaryStatusRecType
      required:
      - BeneficiaryKeys
      - BeneficiaryStatus
      type: object
      properties:
        BeneficiaryKeys:
          $ref: '#/components/schemas/BeneficiaryKeysType'
        BeneficiaryStatus:
          $ref: '#/components/schemas/BeneficiaryStatusType'
      description: Details of the updated status of a beneficiary
    RecCtrlInType:
      title: RecCtrlInType
      type: object
      properties:
        MaxRecLimit:
          type: integer
          description: Maximum Record Limit. This is the maximum number of records that the server should add to the result set which is available to satisfy this request.
          format: int64
        Cursor:
          maxLength: 250
          type: string
          description: Cursor. Next Record Pointer Included in the response only if additional records are available.
      description: Maximum number of records to be processed within a single response as specified by the client
    BeneficiarySelType:
      title: BeneficiarySelType
      type: object
      properties:
        BeneficiaryKeys:
          $ref: '#/components/schemas/BeneficiaryKeysType'
        AcctKeys:
          $ref: '#/components/schemas/AcctKeysType'
      description: Selection criteria to retrieve the beneficiary records
    BeneficiaryInqRqType:
      title: BeneficiaryInqRqType
      required:
      - BeneficiarySel
      type: object
      properties:
        RecCtrlIn:
          $ref: '#/components/schemas/RecCtrlInType'
        BeneficiarySel:
          $ref: '#/components/schemas/BeneficiarySelType'
    RecCtrlOutType:
      title: RecCtrlOutType
      required:
      - SentRecCount
      type: object
      properties:
        SentRecCount:
          type: integer
          description: Total number of records that matched the selection criteria and returned in the response message
          format: int64
      description: Information retrieved for the criteria specified in the RecCtrlIn aggregate of the request message
    BeneficiaryRecType:
      title: BeneficiaryRecType
      required:
      - BeneficiaryInfo
      - BeneficiaryKeys
      - BeneficiaryStatus
      type: object
      properties:
        BeneficiaryKeys:
          $ref: '#/components/schemas/BeneficiaryKeysType'
        BeneficiaryInfo:
          $ref: '#/components/schemas/BeneficiaryInfoType'
        BeneficiaryStatus:
          $ref: '#/components/schemas/BeneficiaryStatusType'
      description: Details of the beneficiary record returned in the response for the specified search criteria
    BeneficiaryInqRsType:
      title: BeneficiaryInqRsType
      required:
      - Status
      type: object
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        RecCtrlOut:
          $ref: '#/components/schemas/RecCtrlOutType'
        BeneficiaryRec:
          type: array
          description: Details of the beneficiary record returned in the response for the specified search criteria
          items:
            $ref: '#/components/schemas/BeneficiaryRecType'
    EFXHeader:
      required:
      - OrganizationId
      type: string
      properties:
        OrganizationId:
          type: string
        TrnId:
          maxLength: 36
          type: string
        VendorId:
          type: string
          description: An identifier, supplied by Fiserv, that represents the vendor using  this API service.
        Context:
          $ref: '#/components/schemas/Context'
      example: '{ "TrnId": "f262cfa4-9da4-4a10-b48c-2e947ce3e66c", "OrganizationId": "PRMOrg10", "VendorId": "112233", "Context":{ "Channel": "WEB" } }'
    Context:
      type: object
      properties:
        ClientAppName:
          maxLength: 40
          type: string
          description: Client Application Name of the application making the service request (e.g. Architect, Commercial Center, etc.).
        Channel:
          type: string
          description: Indicates the channel used by the client application.
        ClientDateTime:
          type: string
          description: Client date and time as reported by the client application that is making the service request.
          format: date-time
        ClientTerminalSeqNum:
          maxLength: 36
          type: string
          description: Also known as Trace Number or Sequence in some systems. Used to allow the client terminal to set a unique identifier for the transaction. When used by a Network defined transaction the value of this identifier is typically set to narrow character of 12.
        OriginatorType:
          type: integer
          description: "\"The type of organization that the originator represents. This is usually a coded value representing the industry that the organization operates in. It contains the SIC code. For ISO 8583 (DE18) the element is restricted to narrow character of maximum length of 4.\nOriginator Type codes that apply to financialinstitutions are:\n  6010 - Financial institution—bank, savings and loan (S and L), or credit union  \n  6011 - Financial institution—ATM \n  6012 - Financial institution—merchandise sale \n  6999 - Financial\ninstitution—home banking\""
          format: int64
        TerminalIdent:
          maxLength: 36
          type: string
          description: Unique code identifying a terminal at the card acceptor locatio (such as terminal code or terminal number of ATM). See For ISO 8583 (DE41) the element is restricted to a narrow character with maximum length of 8.
        TerminalAddr1:
          maxLength: 64
          type: string
        TerminalAddr2:
          maxLength: 64
          type: string
        TerminalAddr3:
          maxLength: 64
          type: string
        TerminalAddr4:
          maxLength: 64
          type: string
        TerminalCity:
          maxLength: 32
          type: string
        TerminalCounty:
          maxLength: 32
          type: string
        TerminalStateProv:
          maxLength: 32
          type: string
          description: State Province. ISO 3166-2:US codes.
        TerminalPostalCode:
          maxLength: 11
          type: string
          description: Postal Code is ZipCode in the US.
        TerminalCountryCodeSource:
          type: string
          description: Country code source.ISO3166-Numeric, ISO3166-Alpha-3
          enum:
          - ISO3166Numeric
          - ISO3166Alpha3
        TerminalCountryCodeValue:
          maxLength: 80
          type: string
        PhoneType:
          type: string
        PhoneNum:
          type: string
        PhoneExchange:
          type: string
        TerminalOwnerName:
          maxLength: 40
          type: string
          description: Name of the owner or operator of the terminal.  For ISO 8583 (DE43) the element is restricted to C-15.
        SystTraceAuditNum:
          maxLength: 36
          type: string
          description: Number assigned by the transaction originator to assist in identifying a transaction uniquely. The trace number remains unchanged for all messages throughout the life of a transaction. This number is not a terminal receipt number. The originating processor increments the trace number by one for each transaction sent to the switch. For ISO 8583 (DE11) the element is restricted to NC-6
        NetworkIdent:
          maxLength: 80
          type: string
          description: Identifies the interchange network for the transaction. The transaction is applied to the specified network settlement counts and balances. For ISO 8583 (DE62) the element is restricted to NC-6
        NetworkRefIdent:
          maxLength: 36
          type: string
          description: Document reference supplied by the system retaining the original source document and used to assist in locating that document. The acquirer of a transaction assigns this number. The issuer processor must retain it in the event that a chargeback is submitted for the transaction. For ISO 8583 (DE37) the element is restricted to C-12
        AcquirerIdent:
          maxLength: 36
          type: string
          description: Identifies the acquirer of the authorization or financial transaction. It is a mandatory element in all authorization and financial messages and does not change throughout the life of a transaction. EPOC considers the acquirer as the terminal owner for reporting purposes. For ISO 8583 (DE32) the element is restricted to C-12
        AcquirerCountryCodeSource:
          type: string
          description: Country code source.ISO3166-Numeric, ISO3166-Alpha-3
          enum:
          - US
          - IND
        AcquirerCountryCodeValue:
          type: string
        MerchNum:
          maxLength: 23
          type: string
          description: Merchant Number. For ISO 8583 (DE42) the element is restricted to C-15
        SettlementDate:
          type: string
          description: This is the date on which the transaction will be settled. Used by ISO 8583 (DE63)
          format: date
        SettlementIdent:
          maxLength: 36
          type: string
          description: This is the identification of the settlement account in which the transaction will be settled.
        BusinessApplIdent:
          type: string
          description: This is the identification of the settlement account in which the transaction will be settled.
        BranchIdent:
          maxLength: 22
          type: string
        TellerIdent:
          type: string
        TillIdent:
          type: string
        AMPMCode:
          type: string
          enum:
          - AM
          - PM
        ReentryType:
          type: string
          enum:
          - Manual
          - Auto
    StatusType:
      title: StatusType
      required:
      - Severity
      - StatusCode
      - StatusDesc
      - SvcProviderName
      type: object
      properties:
        Id:
          type: string
          description: Status identification number.
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              -  Cleartouch
              -  DNA
              -  Precision
              -  Premier
              -  Signature
        ServerStatusCode:
          maxLength: 20
          type: string
          description: Server status code of the service provider's application.
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        OvrdExceptionInd:
          type: boolean
          description: Flag to indicate whether the exception can be overridden by resubmitting the request message.
        SubjectRole:
          type: string
          description: Authorization level required to override, such as Teller and Supervisor.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
        ContentHTML:
          type: string
          description: Response status in HTML format. This parameter returns only in some cases.
        AdditionalStatus:
          type: array
          description: Details of the additional status of the response message. This aggrigate can appear once for each additional status that the server is expected to provide.
          items:
            $ref: '#/components/schemas/AdditionalStatusType'
      description: Details of the API response messages.
    AdditionalStatusType:
      title: AdditionalStatusType
      type: object
      properties:
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> for more information.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              - Cleartouch
              - DNA
              - Precision
              - Premier
              - Signature
        ServerStatusCode:
          maxLength: 20
          type: string
          description: 'Server status code of the service provider''s application.  '
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        OvrdExceptionInd:
          type: boolean
          description: Flag that indicates whether the exception can be overridden by resubmitting the request message.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
  examples:
    "401-Premier":
      value:
        Status:
          StatusCode: "1740"
          StatusDesc: Authentication Failed
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "401"
          ServerStatusDesc: Unauthorized
    "422-Premier":
      value:
        Status:
          StatusCode: "1090"
          StatusDesc: Invalid Value
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "422"
          ServerStatusDesc: Unprocessable Entity
    "500-Premier":
      value:
        Status:
          StatusCode: "100"
          StatusDesc: General Error
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "500"
          ServerStatusDesc: Internal Server Error
    "503-Premier":
      value:
        Status:
          StatusCode: "300"
          StatusDesc: System Not Available
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "503"
          ServerStatusDesc: Service Unavailable
    BeneficiaryInqRq-PRM:
      value:
        BeneficiarySel:
          BeneficiaryKeys:
            AcctKeys:
              AcctId: "1000"
              AcctType: DDA
            BeneficiaryIdent: "1"
    BeneficiaryInqRs-PRM:
      value:
        Status:
          StatusCode: "0"
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        RecCtrlOut:
          SentRecCount: 1
        BeneficiaryRec:
        - BeneficiaryKeys:
            AcctKeys:
              AcctId: "1000"
              AcctType: DDA
            PartyKeys:
              PartyId: "6"
            BeneficiaryIdent: "1"
          BeneficiaryInfo:
            BeneficiaryData:
              FullName: SARAH ADAMS
              TaxIdentType: SSN
              TaxIdent: "432897654"
              BirthDt: 1958-12-11
              PostAddr:
                AddressIdent: "4"
                AddrFormatType: Label
                Addr1: ADDR 90 P.O. BOX 505
                Addr2: ""
                City: RICHMOND
                StateProv: VA
                PostalCode: 18512-4444
                CountryCode:
                  CountryCodeSource: SPCountryCode
                  CountryCodeValue: "00"
                  CountryCodeValueEnumDesc: United States of America
                AddrType: Primary
              BeneficiaryType: Self
              BeneficiaryPercent: 100
          BeneficiaryStatus:
            BeneficiaryStatusCode: Valid
            EffDt: 2021-11-22T02:09:08.313
    BeneficiaryInqRq-DNA:
      value:
        BeneficiarySel:
          AcctKeys:
            AcctId: "183903262300"
            AcctType: RET
    BeneficiaryInqRs-DNA:
      value:
        Status:
          StatusCode: "0"
          StatusDesc: Success
          Severity: Info
          SvcProviderName: DNA
        RecCtrlOut:
          SentRecCount: "10"
        BeneficiaryRec:
        - BeneficiaryKeys:
            AcctKeys:
              AcctId: "183903262300"
              AcctType: RET
            PartyKeys:
              PartyIdentType: OrgNum
              PartyIdent: "664862"
            BeneficiaryIdent: Contingent
          BeneficiaryInfo:
            BeneficiaryData:
              PartyKeys:
                PartyIdentType: OrgNum
                PartyIdent: "664862"
              TaxIdent: {}
              BeneficiaryLevel: CNTG
              BeneficiaryLevelEnumDesc: Contingent
              BeneficiaryType: Brother
              BeneficiaryTypeEnumDesc: Brother
              BeneficiaryPercent: "0.02"
          BeneficiaryStatus:
            BeneficiaryStatusCode: Valid
            EffDt: 2019-02-13T23:34:37.096
        - BeneficiaryKeys:
            AcctKeys:
              AcctId: "183903262300"
              AcctType: RET
            PartyKeys:
              PartyIdentType: OrgNum
              PartyIdent: "664862"
            BeneficiaryIdent: Secondary
          BeneficiaryInfo:
            BeneficiaryData:
              PartyKeys:
                PartyIdentType: OrgNum
                PartyIdent: "664862"
              TaxIdent: {}
              BeneficiaryLevel: SEC
              BeneficiaryLevelEnumDesc: Secondary
              BeneficiaryType: Father
              BeneficiaryTypeEnumDesc: Father
              BeneficiaryPercent: "1.0"
          BeneficiaryStatus:
            BeneficiaryStatusCode: Valid
            EffDt: 2019-02-13T23:34:37.223
        - BeneficiaryKeys:
            AcctKeys:
              AcctId: "183903262300"
              AcctType: RET
            PartyKeys:
              PartyIdentType: PersonNum
              PartyIdent: "1"
            BeneficiaryIdent: Contingent
          BeneficiaryInfo:
            BeneficiaryData:
              PartyKeys:
                PartyIdentType: PersonNum
                PartyIdent: "1"
              FullName: Joe Bxjkca
              TaxIdent: {}
              BeneficiaryLevel: CNTG
              BeneficiaryLevelEnumDesc: Contingent
              BeneficiaryType: Brother
              BeneficiaryTypeEnumDesc: Brother
              BeneficiaryPercent: "0.02"
          BeneficiaryStatus:
            BeneficiaryStatusCode: Valid
            EffDt: 2019-02-13T23:34:37.226
        - BeneficiaryKeys:
            AcctKeys:
              AcctId: "183903262300"
              AcctType: RET
            PartyKeys:
              PartyIdentType: PersonNum
              PartyIdent: "1"
            BeneficiaryIdent: PrimaryNonDesignated
          BeneficiaryInfo:
            BeneficiaryData:
              PartyKeys:
                PartyIdentType: PersonNum
                PartyIdent: "1"
              FullName: Joe Bxjkca
              TaxIdent: {}
              BeneficiaryLevel: PRI
              BeneficiaryLevelEnumDesc: Primary Non-Designated
              BeneficiaryType: Mother
              BeneficiaryTypeEnumDesc: Mother
              BeneficiaryPercent: "1.0"
          BeneficiaryStatus:
            BeneficiaryStatusCode: Valid
            EffDt: 2019-02-13T23:34:37.362
        - BeneficiaryKeys:
            AcctKeys:
              AcctId: "183903262300"
              AcctType: RET
            PartyKeys:
              PartyIdentType: PersonNum
              PartyIdent: "1"
            BeneficiaryIdent: Secondary
          BeneficiaryInfo:
            BeneficiaryData:
              PartyKeys:
                PartyIdentType: PersonNum
                PartyIdent: "1"
              FullName: Joe Bxjkca
              TaxIdent: {}
              BeneficiaryLevel: SEC
              BeneficiaryLevelEnumDesc: Secondary
              BeneficiaryType: Father
              BeneficiaryTypeEnumDesc: Father
              BeneficiaryPercent: "1.0"
          BeneficiaryStatus:
            BeneficiaryStatusCode: Valid
            EffDt: 2019-02-13T23:34:37.365
        - BeneficiaryKeys:
            AcctKeys:
              AcctId: "183903262300"
              AcctType: RET
            PartyKeys:
              PartyIdentType: PersonNum
              PartyIdent: "280907"
            BeneficiaryIdent: Contingent
          BeneficiaryInfo:
            BeneficiaryData:
              PartyKeys:
                PartyIdentType: PersonNum
                PartyIdent: "280907"
              FullName: Stephen Hnvmo
              TaxIdent: "311508683"
              PostAddr:
                AddressIdent: PRI
                AddrFormatType: Parsed
                Street: Gq Nhr 37
                City: N223
                StateProv: PA
                PostalCode: 16102-0068
                CountryCode:
                  CountryCodeSource: ISO3166-Alpha-3
                  CountryCodeValue: USA
                AddrType: Primary
              BeneficiaryLevel: CNTG
              BeneficiaryLevelEnumDesc: Contingent
              BeneficiaryType: Brother
              BeneficiaryTypeEnumDesc: Brother
              BeneficiaryPercent: "2.0"
          BeneficiaryStatus:
            BeneficiaryStatusCode: Valid
            EffDt: 2019-02-13T23:34:37.367
        - BeneficiaryKeys:
            AcctKeys:
              AcctId: "183903262300"
              AcctType: RET
            PartyKeys:
              PartyIdentType: PersonNum
              PartyIdent: "282623"
            BeneficiaryIdent: Contingent
          BeneficiaryInfo:
            BeneficiaryData:
              PartyKeys:
                PartyIdentType: PersonNum
                PartyIdent: "282623"
              FullName: Elaine Xxzzhxz
              TaxIdent: "784686351"
              PostAddr:
                AddressIdent: PRI
                AddrFormatType: Parsed
                Street: 4408 Lqwxqn Is
                City: F543
                StateProv: PA
                PostalCode: 16034-9646
                CountryCode:
                  CountryCodeSource: ISO3166-Alpha-3
                  CountryCodeValue: USA
                AddrType: Primary
              BeneficiaryLevel: CNTG
              BeneficiaryLevelEnumDesc: Contingent
              BeneficiaryType: Brother
              BeneficiaryTypeEnumDesc: Brother
              BeneficiaryPercent: "20.0"
          BeneficiaryStatus:
            BeneficiaryStatusCode: Valid
            EffDt: 2019-02-13T23:34:37.369
        - BeneficiaryKeys:
            AcctKeys:
              AcctId: "183903262300"
              AcctType: RET
            PartyKeys:
              PartyIdentType: PersonNum
              PartyIdent: "1828343"
            BeneficiaryIdent: Contingent
          BeneficiaryInfo:
            BeneficiaryData:
              PartyKeys:
                PartyIdentType: PersonNum
                PartyIdent: "1828343"
              FullName: Frank Aaatcumd
              TaxIdent: "069605651"
              PostAddr:
                AddressIdent: SEA
                AddrFormatType: Parsed
                HouseNum: EBAY EBAY EBAY
                Street: CHECK
                AddrDefinedData:
                  DataIdent: APCX
                  Value: TEST TEST
                City: Schenectady
                StateProv: NY
                PostalCode: 12345-0000
                CountryCode:
                  CountryCodeSource: ISO3166-Alpha-3
                  CountryCodeValue: USA
                AddrType: Primary
              BeneficiaryLevel: CNTG
              BeneficiaryLevelEnumDesc: Contingent
              BeneficiaryType: Brother
              BeneficiaryTypeEnumDesc: Brother
              BeneficiaryPercent: "0.02"
          BeneficiaryStatus:
            BeneficiaryStatusCode: Valid
            EffDt: 2019-02-13T23:34:37.371
        - BeneficiaryKeys:
            AcctKeys:
              AcctId: "183903262300"
              AcctType: RET
            PartyKeys:
              PartyIdentType: PersonNum
              PartyIdent: "10000017445"
            BeneficiaryIdent: Contingent
          BeneficiaryInfo:
            BeneficiaryData:
              PartyKeys:
                PartyIdentType: PersonNum
                PartyIdent: "10000017445"
              FullName: Suraiya Abpew
              TaxIdent: "736987770"
              BeneficiaryLevel: UDFV
              BeneficiaryLevelEnumDesc: Bank defined
              BeneficiaryType: Trust
              BeneficiaryTypeEnumDesc: Trust
              BeneficiaryPercent: "100.0"
          BeneficiaryStatus:
            BeneficiaryStatusCode: Valid
            EffDt: 2019-02-13T23:34:37.495
        - BeneficiaryKeys:
            AcctKeys:
              AcctId: "183903262300"
              AcctType: RET
            PartyKeys:
              PartyIdentType: PersonNum
              PartyIdent: "100000271398"
            BeneficiaryIdent: PrimaryDesignated
          BeneficiaryInfo:
            BeneficiaryData:
              PartyKeys:
                PartyIdentType: PersonNum
                PartyIdent: "100000271398"
              FullName: Joe Banker
              TaxIdent: "111222333"
              BeneficiaryLevel: PRID
              BeneficiaryLevelEnumDesc: Primary Designated
              BeneficiaryType: Trust
              BeneficiaryTypeEnumDesc: {}
              BeneficiaryPercent: "100.0"
          BeneficiaryStatus:
            BeneficiaryStatusCode: Valid
            EffDt: 2019-02-13T23:34:37.557
