---
openapi: 3.0.0
info:
  title: Host Logon Service - Get Host Logon
  description: Host logon service is used to authenticate users and provide user authorization (system assertions/entitlements).
  version: 11.0.0_Secured
servers:
- url: /
paths:
  /hostlogon:
    post:
      tags:
      - Get Host Logon
      summary: Get Host Logon.
      description: "Returns user assertions/ entitlements when the user credentials are passed in the request\n <br><br>\nFor more information about the Operations and Servicing domain <a href=\"../docs/?path=docs/fintechs/servicing.md\" title=\"Click to open\">click here.</a> <br><br> <b>Relates to:</b>\n  <ul> \n    <li><a href=\"../docs/?path=docs/banks-and-CU/deposits.md\" title=\"Click to open\">Deposits</a></li>\n    <li><a href=\"../docs/?path=docs/banks-and-CU/loans.md\" title=\"Click to open\">Loans</a></li>\n    <li><a href=\"../docs/?path=docs/banks-and-CU/bank-servicing.md\" title=\"Click to open\">Bank Servicing</a></li>\n  </ul>\n  \n  <br>\n  <blockquote style=\"border-left: 0.375em solid #40a9ff; background-color: #e6f7ff; border-radius: 3px; padding: 1em;\" > To view provider specific implementation notes and applicable fields, <a target=\"_blank\" title=\"Click to open in a new tab\" href=\"../docs/?path=docs/implementation-notes/Servicing/HostLogonAdd-ImplNotes.md\">click here</a>.</blockquote>"
      parameters:
      - name: EFXHeader
        in: header
        description: EFX Header is a common and required component for all API calls, it contains authentication and client-related parameters. Please note that the header parameters should be sent as a JSON object under the EFXHeader parameter. To view the list of header parameters, <a href="../docs?path=docs/api-ref-EFX-header.md" title="Click to open"> click here.</a>
        required: true
        schema:
          $ref: '#/components/schemas/EFXHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HostLogonAddRqType'
            examples:
              Sample Premier:
                $ref: '#/components/examples/HostLogonRequest-Premier'
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostLogonAddRsType'
              examples:
                Sample Premier:
                  $ref: '#/components/examples/HostLogonResponse-Premier'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostLogonAddRsType'
      deprecated: false
      x-group-name: Host Logon Service
      x-proxy-name: Get Host Logon
      x-child-product-name: Operations and Servicing
components:
  schemas:
    SubjectElementType:
      title: SubjectElementType
      type: object
      properties:
        Path:
          type: string
          description: Path of the element (in XPath absolute notation format) where the error occurred.  If the error occurred at the top-level element, then name of the element is returned in the response.
        ServerPath:
          maxLength: 256
          type: string
          description: Server Path is the Service Providerâ€™s identification of the field in their schema, such as an XPath, field ID, or field name that is associated with the ServerStatusCode. If this element is set, it must be returned in the ServerPath element of the OvrdExceptionData aggregate if the exception is being overridden.
        Value:
          maxLength: 256
          type: string
          description: Human readable information of the EFX data value of the element to be overridden. This value should not be provided for the fields that cannot be represented as a string, for example, binary data.
      description: Information about the subject element
    AssertionTypeType:
      title: AssertionTypeType
      type: string
      description: 'Type of assertion that specifies the area of system or function to which user may or may not have access based upon the <b>AssertionValueInd</b> value. <br> To view the allowed values, please refer the <a target="_blank" href="../docs/?path=docs/implementation-notes/Servicing/HostLogonAdd-ImplNotes.md" >provider specific implementation notes</a>. '
      example: SDA
      enum:
      - SDA
      - CDA
      - CRD
      - LOAN
      - DDA
      - Customer
      - BankAdmin
    OperationType:
      title: OperationType
      type: string
      description: 'Type of operation to which the user may or may not have access based upon the <b>AssertionValueInd</b> value. <br> To view the allowed values, please refer the <a target="_blank" href="../docs/?path=docs/implementation-notes/Servicing/HostLogonAdd-ImplNotes.md" >provider specific implementation notes</a>. '
      example: Add
      enum:
      - Add
      - Inq
      - Mod
      - Del
    AssertionType:
      title: AssertionType
      required:
      - AssertionType
      - AssertionValueInd
      type: object
      properties:
        AssertionType:
          $ref: '#/components/schemas/AssertionTypeType'
        AssertionValueInd:
          type: boolean
          description: Flag to indicate if the user has permission to access the <b>AssertionType</b> and <b>Operation</b> values returned in the response.
        Operation:
          $ref: '#/components/schemas/OperationType'
    Binary128Type:
      title: Binary128Type
      required:
      - BinData
      type: object
      properties:
        BinLength:
          type: integer
          description: Binary Length
          format: int64
        BinData:
          type: string
          description: Binary Data
          format: binary
    CryptPswdType:
      title: CryptPswdType
      description: 'Encrypted password for security '
      allOf:
      - $ref: '#/components/schemas/Binary128Type'
      - type: object
    SubjectPswdType:
      title: SubjectPswdType
      type: object
      properties:
        CryptType:
          maxLength: 80
          type: string
          description: Type of encryption used for transmitting authentication information
        Pswd:
          maxLength: 32
          type: string
          description: Password required for the login
        CryptPswd:
          $ref: '#/components/schemas/CryptPswdType'
      description: 'Information related to user password '
    SecTokenLoginType:
      title: SecTokenLoginType
      required:
      - LoginName
      - SubjectPswd
      type: object
      properties:
        LoginName:
          maxLength: 255
          type: string
          description: 'Provider defined unique identification name of the user for which the credentials/entitlements to be retrieved. '
        SubjectPswd:
          $ref: '#/components/schemas/SubjectPswdType'
        TrnDt:
          pattern: ^\[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?$
          type: string
          description: 'Transaction date when teller or any other credentials are used to perform log on transaction for authentication purpose. <br> Format: yyyy-MM-ddTHH:mm:ss.SSS'
          example: 2021-12-31T23:59:59.999
      description: Security Token Login
    HostCredentialsRqHdrType:
      title: HostCredentialsRqHdrType
      type: object
      properties:
        SecTokenLogin:
          $ref: '#/components/schemas/SecTokenLoginType'
      description: Security token to authenticate user in a login process.
    HostCredentialsRsHdrType:
      title: HostCredentialsRsHdrType
      type: object
      properties:
        SessKey:
          maxLength: 64
          type: string
          description: Session key of a user which is used in future communication with ESF for the same user.
        AuthCode:
          maxLength: 256
          type: string
          description: Authentication code
        UserCode:
          maxLength: 10
          type: string
          description: User code
        UserName:
          maxLength: 256
          type: string
          description: Name of the user.
        Assertion:
          type: array
          description: Assertion details to determine the entitlements of the user.
          items:
            $ref: '#/components/schemas/AssertionType'
      description: Details of the host or user entitlements.
    HostLogonAddRqType:
      title: HostLogonRqType
      required:
      - HostCredentialsRqHdr
      type: object
      properties:
        HostCredentialsRqHdr:
          $ref: '#/components/schemas/HostCredentialsRqHdrType'
      description: Credentials of the host or user whose entitlements to be retrieved.
    SubjectRoleType:
      title: SubjectRoleType
      type: string
      example: Teller
      enum:
      - Teller
      - Supervisor
    HostLogonAddRsType:
      title: HostLogonRsType
      required:
      - Status
      type: object
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        HostCredentialsRsHdr:
          $ref: '#/components/schemas/HostCredentialsRsHdrType'
    EFXHeader:
      required:
      - OrganizationId
      type: string
      properties:
        OrganizationId:
          type: string
        TrnId:
          maxLength: 36
          type: string
        VendorId:
          type: string
          description: An identifier, supplied by Fiserv, that represents the vendor using  this API service.
        Context:
          $ref: '#/components/schemas/Context'
      example: '{ "TrnId": "f262cfa4-9da4-4a10-b48c-2e947ce3e66c", "OrganizationId": "PRMOrg10", "VendorId": "112233", "Context":{ "Channel": "WEB" } }'
    Context:
      type: object
      properties:
        ClientAppName:
          maxLength: 40
          type: string
          description: Client Application Name of the application making the service request (e.g. Architect, Commercial Center, etc.).
        Channel:
          type: string
          description: Indicates the channel used by the client application.
        ClientDateTime:
          type: string
          description: Client date and time as reported by the client application that is making the service request.
          format: date-time
        ClientTerminalSeqNum:
          maxLength: 36
          type: string
          description: Also known as Trace Number or Sequence in some systems. Used to allow the client terminal to set a unique identifier for the transaction. When used by a Network defined transaction the value of this identifier is typically set to narrow character of 12.
        OriginatorType:
          type: integer
          description: "\"The type of organization that the originator represents. This is usually a coded value representing the industry that the organization operates in. It contains the SIC code. For ISO 8583 (DE18) the element is restricted to narrow character of maximum length of 4.\nOriginator Type codes that apply to financialinstitutions are:\n  6010 - Financial institutionâ€”bank, savings and loan (S and L), or credit union  \n  6011 - Financial institutionâ€”ATM \n  6012 - Financial institutionâ€”merchandise sale \n  6999 - Financial\ninstitutionâ€”home banking\""
          format: int64
        TerminalIdent:
          maxLength: 36
          type: string
          description: Unique code identifying a terminal at the card acceptor locatio (such as terminal code or terminal number of ATM). See For ISO 8583 (DE41) the element is restricted to a narrow character with maximum length of 8.
        TerminalAddr1:
          maxLength: 64
          type: string
        TerminalAddr2:
          maxLength: 64
          type: string
        TerminalAddr3:
          maxLength: 64
          type: string
        TerminalAddr4:
          maxLength: 64
          type: string
        TerminalCity:
          maxLength: 32
          type: string
        TerminalCounty:
          maxLength: 32
          type: string
        TerminalStateProv:
          maxLength: 32
          type: string
          description: State Province. ISO 3166-2:US codes.
        TerminalPostalCode:
          maxLength: 11
          type: string
          description: Postal Code is ZipCode in the US.
        TerminalCountryCodeSource:
          type: string
          description: Country code source.ISO3166-Numeric, ISO3166-Alpha-3
          enum:
          - ISO3166Numeric
          - ISO3166Alpha3
        TerminalCountryCodeValue:
          maxLength: 80
          type: string
        PhoneType:
          type: string
        PhoneNum:
          type: string
        PhoneExchange:
          type: string
        TerminalOwnerName:
          maxLength: 40
          type: string
          description: Name of the owner or operator of the terminal.  For ISO 8583 (DE43) the element is restricted to C-15.
        SystTraceAuditNum:
          maxLength: 36
          type: string
          description: Number assigned by the transaction originator to assist in identifying a transaction uniquely. The trace number remains unchanged for all messages throughout the life of a transaction. This number is not a terminal receipt number. The originating processor increments the trace number by one for each transaction sent to the switch. For ISO 8583 (DE11) the element is restricted to NC-6
        NetworkIdent:
          maxLength: 80
          type: string
          description: Identifies the interchange network for the transaction. The transaction is applied to the specified network settlement counts and balances. For ISO 8583 (DE62) the element is restricted to NC-6
        NetworkRefIdent:
          maxLength: 36
          type: string
          description: Document reference supplied by the system retaining the original source document and used to assist in locating that document. The acquirer of a transaction assigns this number. The issuer processor must retain it in the event that a chargeback is submitted for the transaction. For ISO 8583 (DE37) the element is restricted to C-12
        AcquirerIdent:
          maxLength: 36
          type: string
          description: Identifies the acquirer of the authorization or financial transaction. It is a mandatory element in all authorization and financial messages and does not change throughout the life of a transaction. EPOC considers the acquirer as the terminal owner for reporting purposes. For ISO 8583 (DE32) the element is restricted to C-12
        AcquirerCountryCodeSource:
          type: string
          description: Country code source.ISO3166-Numeric, ISO3166-Alpha-3
          enum:
          - US
          - IND
        AcquirerCountryCodeValue:
          type: string
        MerchNum:
          maxLength: 23
          type: string
          description: Merchant Number. For ISO 8583 (DE42) the element is restricted to C-15
        SettlementDate:
          type: string
          description: This is the date on which the transaction will be settled. Used by ISO 8583 (DE63)
          format: date
        SettlementIdent:
          maxLength: 36
          type: string
          description: This is the identification of the settlement account in which the transaction will be settled.
        BusinessApplIdent:
          type: string
          description: This is the identification of the settlement account in which the transaction will be settled.
        BranchIdent:
          maxLength: 22
          type: string
        TellerIdent:
          type: string
        TillIdent:
          type: string
        AMPMCode:
          type: string
          enum:
          - AM
          - PM
        ReentryType:
          type: string
          enum:
          - Manual
          - Auto
    StatusType:
      title: StatusType
      required:
      - Severity
      - StatusCode
      - StatusDesc
      - SvcProviderName
      type: object
      properties:
        AdditionalStatus:
          type: array
          description: Details of the additional status of the response message. This aggrigate can appear once for each additional status that the server is expected to provide.
          items:
            $ref: '#/components/schemas/AdditionalStatusType'
        ContentHTML:
          type: string
          description: Response status in HTML format. This parameter returns only in some cases.
        Id:
          type: string
          description: Status identification number.
        OvrdExceptionInd:
          type: boolean
          description: Flag to indicate whether the exception can be overridden by resubmitting the request message.
        ServerStatusCode:
          maxLength: 20
          type: string
          description: Server status code of the service provider's application.
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
        SubjectRole:
          type: string
          description: Authorization level required to override, such as Teller and Supervisor.
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              -  Cleartouch
              -  DNA
              -  Precision
              -  Premier
              -  Signature
      description: Details of the API response messages.
    AdditionalStatusType:
      title: AdditionalStatusType
      type: object
      properties:
        OvrdExceptionInd:
          type: boolean
          description: Flag that indicates whether the exception can be overridden by resubmitting the request message.
        ServerStatusCode:
          maxLength: 20
          type: string
          description: 'Server status code of the service provider''s application.  '
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> for more information.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              - Cleartouch
              - DNA
              - Precision
              - Premier
              - Signature
    SeverityType:
      title: SeverityType
      type: string
      description: Severity type of the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
      enum:
      - Error
      - Warning
      - Info
  examples:
    "401-Premier":
      value:
        Status:
          StatusCode: "1740"
          StatusDesc: Authentication Failed
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "401"
          ServerStatusDesc: Unauthorized
    "422-Premier":
      value:
        Status:
          StatusCode: "1090"
          StatusDesc: Invalid Value
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "422"
          ServerStatusDesc: Unprocessable Entity
    "500-Premier":
      value:
        Status:
          StatusCode: "100"
          StatusDesc: General Error
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "500"
          ServerStatusDesc: Internal Server Error
    "503-Premier":
      value:
        Status:
          StatusCode: "300"
          StatusDesc: System Not Available
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "503"
          ServerStatusDesc: Service Unavailable
    HostLogonRequest-Premier:
      value:
        HostCredentialsRqHdr:
          SecTokenLogin:
            LoginName: ESFPRM10
            SubjectPswd:
              Pswd: NL08oT2lmMwJqekV+mN8XdVTRspbNKh
    HostLogonResponse-Premier:
      value:
        Status:
          StatusCode: "0"
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        HostCredentialsRsHdr:
          SessKey: 05862572-fe8b-4c27-8948-e49bfd5f24f8
          AuthCode: "1234"
          UserCode: "1234"
          UserName: ESFPRM10
          Assertion:
          - AssertionType: BankAdmin
            AssertionValueInd: true
          - AssertionType: Customer
            AssertionValueInd: true
            Operation: Inq
          - AssertionType: Customer
            AssertionValueInd: true
            Operation: Mod
          - AssertionType: Customer
            AssertionValueInd: true
            Operation: Add
          - AssertionType: DDA
            AssertionValueInd: true
            Operation: Add
          - AssertionType: SDA
            AssertionValueInd: true
            Operation: Add
          - AssertionType: CDA
            AssertionValueInd: true
            Operation: Add
          - AssertionType: LOAN
            AssertionValueInd: true
            Operation: Add
          - AssertionType: CRD
            AssertionValueInd: true
            Operation: Add
    HostLogonRequest-Cleartouch:
      value:
        HostCredentialsRqHdr:
          SecTokenLogin:
            LoginName: esf-Btat2-Teller
            SubjectPswd:
              Pswd: Fiserv1234!
    HostLogonResponse-Cleartouch:
      value:
        Status:
          StatusCode: "0"
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Cleartouch
        HostCredentialsRsHdr:
          SessKey: afc7456b-f2c7-4dd7-a7fc-64ccc0e2c590
    HostLogonRequest-Precision:
      value:
        HostCredentialsRqHdr:
          SecTokenLogin:
            LoginName: LoginName
            SubjectPswd:
              Pswd: Fiserv1234!
    HostLogonResponse-Precision:
      value:
        Status:
          StatusCode: 0
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Precision
        HostCredentialsRsHdr:
          SessKey: 8a3b025e-31d6-443d-97b7-SessKey1234
          AuthCode: LoginName
          Assertion:
          - AssertionType: CRD
            AssertionValueInd: "true"
            Operation: Add
          - AssertionType: CDA
            AssertionValueInd: "true"
            Operation: Add
          - AssertionType: CustomerModification
            AssertionValueInd: "true"
            Operation: Mod
          - AssertionType: CustomerInquiry
            AssertionValueInd: "true"
            Operation: Inq
          - AssertionType: CustomerCreation
            AssertionValueInd: "true"
            Operation: Add
          - AssertionType: DDA
            AssertionValueInd: "true"
            Operation: Add
          - AssertionType: BankAdmin
            AssertionValueInd: "true"
          - AssertionType: LOAN
            AssertionValueInd: "false"
            Operation: Add
          - AssertionType: SDA
            AssertionValueInd: "true"
            Operation: Add
