---
openapi: 3.0.0
info:
  title: Host Logon Service
  description: Host logon service is used to authenticate users and provide user authorization (system assertions/entitlements).
  version: 11.0.0
servers:
- url: /
paths:
  /hostlogon:
    post:
      tags:
      - Get Host Logon
      summary: Get Host Logon.
      description: "Returns user assertions/ entitlements when the user credentials are passed in the request\n <br><br>\nTo view provider specific implementation notes and applicable fields, <a href=\"../docs/?path=docs/implementation-notes/Servicing/HostLogon/HostLogonAdd-ImplNotes.md\">click here</a>. <br> For more information about the Operations and Servicing domain <a href=\"../docs/?path=docs/fintechs/servicing.md\" title=\"Click to open\">click here.</a> <br><br> <b>Relates to:</b>\n  <ul> \n    <li><a href=\"../docs/?path=docs/banks-and-CU/deposits.md\" title=\"Click to open\">Deposits</a></li>\n    <li><a href=\"../docs/?path=docs/banks-and-CU/loans.md\" title=\"Click to open\">Loans</a></li>\n    <li><a href=\"../docs/?path=docs/banks-and-CU/bank-servicing.md\" title=\"Click to open\">Bank Servicing</a></li>\n  </ul>"
      parameters:
      - name: EFXHeader
        in: header
        description: EFX Header is a common and required component for all API calls, it contains authentication and client-related parameters. Please note that the header parameters should be sent as a JSON object under the EFXHeader parameter. To view the list of header parameters, <a href="../docs?path=docs/api-ref-EFX-header.md" title="Click to open">click here.</a>
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/EFXHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HostLogonAddRqType'
            examples:
              Sample Banking:
                $ref: '#/components/examples/HostLogonRequest-Premier'
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostLogonAddRsType'
              examples:
                Sample Banking:
                  $ref: '#/components/examples/HostLogonResponse-Premier'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostLogonAddRsType'
              examples:
                "401":
                  $ref: '#/components/examples/401-Premier'
        "422":
          description: Un-processable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostLogonAddRsType'
              examples:
                "422":
                  $ref: '#/components/examples/422-Premier'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostLogonAddRsType'
              examples:
                "500":
                  $ref: '#/components/examples/500-Premier'
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostLogonAddRsType'
              examples:
                "503":
                  $ref: '#/components/examples/503-Premier'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostLogonAddRsType'
      deprecated: false
      x-group-name: Host Logon Service
      x-proxy-name: Get Host Logon
      x-child-product-name: Operations and Servicing
components:
  schemas:
    EFXHeader:
      required:
      - OrganizationId
      type: string
      properties:
        OrganizationId:
          type: string
        TrnId:
          maxLength: 36
          type: string
        VendorId:
          type: string
          description: An identifier, supplied by Fiserv, that represents the vendor using  this API service.
        Context:
          $ref: '#/components/schemas/Context'
      example: '{ "TrnId": "622182", "OrganizationId": "PRMOrg10", "VendorId": "112233", "Context":{ "Channel": "WEB" } }'
    Context:
      type: object
      properties:
        ClientAppName:
          maxLength: 40
          type: string
          description: Client Application Name of the application making the service request (e.g. Architect, Commercial Center, etc.).
        Channel:
          type: string
          description: Indicates the channel used by the client application.
        ClientDateTime:
          pattern: ^\[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?$
          type: string
          description: Client date and time as reported by the client application that is making the service request.
        ClientTerminalSeqNum:
          maxLength: 36
          type: string
          description: Also known as Trace Number or Sequence in some systems. Used to allow the client terminal to set a unique identifier for the transaction. When used by a Network defined transaction the value of this identifier is typically set to narrow character of 12.
        OriginatorType:
          type: integer
          description: "\"The type of organization that the originator represents. This is usually a coded value representing the industry that the organization operates in. It contains the SIC code. For ISO 8583 (DE18) the element is restricted to narrow character of maximum length of 4.\nOriginator Type codes that apply to financialinstitutions are:\n  6010 - Financial institution—bank, savings and loan (S and L), or credit union  \n  6011 - Financial institution—ATM \n  6012 - Financial institution—merchandise sale \n  6999 - Financial\ninstitution—home banking\"\n"
          format: int64
        TerminalIdent:
          maxLength: 36
          type: string
          description: Unique code identifying a terminal at the card acceptor locatio (such as terminal code or terminal number of ATM). See For ISO 8583 (DE41) the element is restricted to a narrow character with maximum length of 8.
        TerminalAddr1:
          maxLength: 64
          type: string
        TerminalAddr2:
          maxLength: 64
          type: string
        TerminalAddr3:
          maxLength: 64
          type: string
        TerminalAddr4:
          maxLength: 64
          type: string
        TerminalCity:
          maxLength: 32
          type: string
        TerminalCounty:
          maxLength: 32
          type: string
        TerminalStateProv:
          maxLength: 32
          type: string
          description: State Province. ISO 3166-2:US codes.
        TerminalPostalCode:
          maxLength: 11
          type: string
          description: Postal Code is ZipCode in the US.
        TerminalCountryCodeSource:
          type: string
          description: Country code source.ISO3166-Numeric, ISO3166-Alpha-3
          enum:
          - ISO3166Numeric
          - ISO3166Alpha3
        TerminalCountryCodeValue:
          maxLength: 80
          type: string
        PhoneType:
          type: string
        PhoneNum:
          type: string
        PhoneExchange:
          type: string
        TerminalOwnerName:
          maxLength: 40
          type: string
          description: Name of the owner or operator of the terminal.  For ISO 8583 (DE43) the element is restricted to C-15.
        SystTraceAuditNum:
          maxLength: 36
          type: string
          description: Number assigned by the transaction originator to assist in identifying a transaction uniquely. The trace number remains unchanged for all messages throughout the life of a transaction. This number is not a terminal receipt number. The originating processor increments the trace number by one for each transaction sent to the switch. For ISO 8583 (DE11) the element is restricted to NC-6
        NetworkIdent:
          maxLength: 80
          type: string
          description: Identifies the interchange network for the transaction. The transaction is applied to the specified network settlement counts and balances. For ISO 8583 (DE62) the element is restricted to NC-6
        NetworkRefIdent:
          maxLength: 36
          type: string
          description: Document reference supplied by the system retaining the original source document and used to assist in locating that document. The acquirer of a transaction assigns this number. The issuer processor must retain it in the event that a chargeback is submitted for the transaction. For ISO 8583 (DE37) the element is restricted to C-12
        AcquirerIdent:
          maxLength: 36
          type: string
          description: Identifies the acquirer of the authorization or financial transaction. It is a mandatory element in all authorization and financial messages and does not change throughout the life of a transaction. EPOC considers the acquirer as the terminal owner for reporting purposes. For ISO 8583 (DE32) the element is restricted to C-12
        AcquirerCountryCodeSource:
          type: string
          description: Country code source.ISO3166-Numeric, ISO3166-Alpha-3
          enum:
          - US
          - IND
        AcquirerCountryCodeValue:
          type: string
        MerchNum:
          maxLength: 23
          type: string
          description: Merchant Number. For ISO 8583 (DE42) the element is restricted to C-15
        SettlementDate:
          type: string
          description: This is the date on which the transaction will be settled. Used by ISO 8583 (DE63)
          format: date
        SettlementIdent:
          maxLength: 36
          type: string
          description: This is the identification of the settlement account in which the transaction will be settled.
        BusinessApplIdent:
          type: string
          description: This is the identification of the settlement account in which the transaction will be settled.
        BranchIdent:
          maxLength: 22
          type: string
        TellerIdent:
          type: string
        TillIdent:
          type: string
        AMPMCode:
          type: string
          enum:
          - AM
          - PM
        ReentryType:
          type: string
          enum:
          - Manual
          - Auto
    SeverityType:
      title: SeverityType
      type: string
      description: Severity type of the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
      enum:
      - Error
      - Warning
      - Info
    SubjectElementType:
      title: SubjectElementType
      type: object
      properties:
        Path:
          type: string
          description: Path of the element (in XPath absolute notation format) where the error occurred.  If the error occurred at the top-level element, then name of the element is returned in the response.
        ServerPath:
          maxLength: 256
          type: string
          description: Server Path is the Service Provider’s identification of the field in their schema, such as an XPath, field ID, or field name that is associated with the ServerStatusCode. If this element is set, it must be returned in the ServerPath element of the OvrdExceptionData aggregate if the exception is being overridden.
        Value:
          maxLength: 256
          type: string
          description: Human readable information of the EFX data value of the element to be overridden. This value should not be provided for the fields that cannot be represented as a string, for example, binary data.
      description: Information about the subject element
    AdditionalStatusType:
      title: AdditionalStatusType
      type: object
      properties:
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> for more information.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              - Cleartouch
              - DNA
              - Precision
              - Premier
              - Signature
        ServerStatusCode:
          maxLength: 20
          type: string
          description: 'Server status code of the service provider''s application.  '
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        OvrdExceptionInd:
          type: boolean
          description: Flag that indicates whether the exception can be overridden by resubmitting the request message.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
    AssertionTypeType:
      title: AssertionTypeType
      type: string
      example: SDA
      enum:
      - SDA
      - CDA
      - CRD
      - LOAN
      - DDA
      - Customer
      - BankAdmin
    OperationType:
      title: OperationType
      type: string
      example: Add
      enum:
      - Add
      - Inq
      - Mod
      - Del
    AssertionType:
      title: AssertionType
      required:
      - AssertionType
      - AssertionValueInd
      type: object
      properties:
        AssertionType:
          $ref: '#/components/schemas/AssertionTypeType'
        AssertionValueInd:
          type: boolean
          description: Flag to indicate the user have the right to access or permission to perform the action
        Operation:
          $ref: '#/components/schemas/OperationType'
    Binary128Type:
      title: Binary128Type
      required:
      - BinData
      type: object
      properties:
        BinLength:
          type: integer
          description: Binary Length
          format: int64
        BinData:
          type: string
          description: Binary Data
          format: binary
    CryptPswdType:
      title: CryptPswdType
      description: 'Encrypted password for security '
      allOf:
      - $ref: '#/components/schemas/Binary128Type'
      - type: object
    SubjectPswdType:
      title: SubjectPswdType
      type: object
      properties:
        CryptType:
          maxLength: 80
          type: string
          description: Type of encryption used for transmitting authentication information
        Pswd:
          maxLength: 32
          type: string
          description: Password required for the login
        CryptPswd:
          $ref: '#/components/schemas/CryptPswdType'
      description: 'Information related to user password '
    SecTokenLoginType:
      title: SecTokenLoginType
      required:
      - LoginName
      - SubjectPswd
      type: object
      properties:
        LoginName:
          maxLength: 255
          type: string
          description: Unique identification name of the user requesting the entitlements
        SubjectPswd:
          $ref: '#/components/schemas/SubjectPswdType'
      description: Security Token Login
    HostCredentialsRqHdrType:
      title: HostCredentialsRqHdrType
      type: object
      properties:
        SecTokenLogin:
          $ref: '#/components/schemas/SecTokenLoginType'
      description: Security token details for login
    HostCredentialsRsHdrType:
      title: HostCredentialsRsHdrType
      type: object
      properties:
        SessKey:
          maxLength: 64
          type: string
          description: Session key used to establish secure connection for future communication with the ESF for the same user
        AuthCode:
          maxLength: 256
          type: string
          description: Code used for authorization
        UserCode:
          maxLength: 10
          type: string
          description: User Code.
        UserName:
          maxLength: 256
          type: string
          description: Name of the user
        Assertion:
          type: array
          description: Assertion details to determine the entitlements of the user
          items:
            $ref: '#/components/schemas/AssertionType'
      description: Response header details for host credentials
    HostLogonAddRqType:
      title: HostLogonRqType
      required:
      - HostCredentialsRqHdr
      type: object
      properties:
        HostCredentialsRqHdr:
          $ref: '#/components/schemas/HostCredentialsRqHdrType'
      description: Request header details for host credentials
    SubjectRoleType:
      title: SubjectRoleType
      type: string
      example: Teller
      enum:
      - Teller
      - Supervisor
    StatusType:
      title: StatusType
      required:
      - Severity
      - StatusCode
      - StatusDesc
      - SvcProviderName
      type: object
      properties:
        Id:
          type: string
          description: Status identification number.
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              -  Cleartouch
              -  DNA
              -  Precision
              -  Premier
              -  Signature
        ServerStatusCode:
          maxLength: 20
          type: string
          description: Server status code of the service provider's application.
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        OvrdExceptionInd:
          type: boolean
          description: Flag to indicate whether the exception can be overridden by resubmitting the request message.
        SubjectRole:
          type: string
          description: Authorization level required to override, such as Teller and Supervisor.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
        ContentHTML:
          type: string
          description: Response status in HTML format. This parameter returns only in some cases.
        AdditionalStatus:
          type: array
          description: Details of the additional status of the response message. This aggrigate can appear once for each additional status that the server is expected to provide.
          items:
            $ref: '#/components/schemas/AdditionalStatusType'
      description: Details of the API response messages.
    HostLogonAddRsType:
      title: HostLogonRsType
      required:
      - Status
      type: object
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        HostCredentialsRsHdr:
          $ref: '#/components/schemas/HostCredentialsRsHdrType'
  examples:
    "401-Premier":
      value:
        Status:
          StatusCode: "1740"
          StatusDesc: Authentication Failed
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "401"
          ServerStatusDesc: Unauthorized
    "422-Premier":
      value:
        Status:
          StatusCode: "1090"
          StatusDesc: Invalid Value
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "422"
          ServerStatusDesc: Unprocessable Entity
    "500-Premier":
      value:
        Status:
          StatusCode: "100"
          StatusDesc: General Error
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "500"
          ServerStatusDesc: Internal Server Error
    "503-Premier":
      value:
        Status:
          StatusCode: "300"
          StatusDesc: System Not Available
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "503"
          ServerStatusDesc: Service Unavailable
    HostLogonRequest-Premier:
      value:
        HostCredentialsRqHdr:
          SecTokenLogin:
            LoginName: ESFPRM10
            SubjectPswd:
              Pswd: NL08oT2lmMwJqekV+mN8XdVTRspbNKh
    HostLogonResponse-Premier:
      value:
        Status:
          StatusCode: "0"
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        HostCredentialsRsHdr:
          SessKey: 05862572-fe8b-4c27-8948-e49bfd5f24f8
          AuthCode: "1234"
          UserCode: "1234"
          UserName: ESFPRM10
          Assertion:
          - AssertionType: BankAdmin
            AssertionValueInd: true
          - AssertionType: Customer
            AssertionValueInd: true
            Operation: Inq
          - AssertionType: Customer
            AssertionValueInd: true
            Operation: Mod
          - AssertionType: Customer
            AssertionValueInd: true
            Operation: Add
          - AssertionType: DDA
            AssertionValueInd: true
            Operation: Add
          - AssertionType: SDA
            AssertionValueInd: true
            Operation: Add
          - AssertionType: CDA
            AssertionValueInd: true
            Operation: Add
          - AssertionType: LOAN
            AssertionValueInd: true
            Operation: Add
          - AssertionType: CRD
            AssertionValueInd: true
            Operation: Add