---
openapi: 3.0.0
info:
  title: Product Service - Get Product List
  description: Product service supports an inquiry operation to retrieve the list of card, deposit and loan products offered by the financial institution.
  version: 11.0.0
servers:
- url: /
paths:
  /productList/secured:
    post:
      tags:
      - Get Product List
      summary: Get Product List.
      description: "Retrieves the list of products offered by the financial institution. <br><br> For more information about the Operations and Servicing domain <a href=\"../docs/?path=docs/fintechs/servicing.md\" title=\"Click to open\">click here.</a> <br><br> <b>Relates to:</b>\n  <ul> \n    <li><a href=\"../docs/?path=docs/banks-and-CU/deposits.md\" title=\"Click to open\">Deposits</a></li>\n    <li><a href=\"../docs/?path=docs/banks-and-CU/loans.md\" title=\"Click to open\">Loans</a></li>\n    <li><a href=\"../docs/?path=docs/banks-and-CU/bank-servicing.md\" title=\"Click to open\">Bank Servicing</a></li>\n  </ul>\n<br>\n  <blockquote style=\"border-left: 0.375em solid #40a9ff; background-color: #e6f7ff; border-radius: 3px; padding: 1em;\" > To view provider specific implementation notes and applicable fields, <a target=\"_blank\" title=\"Click to open in a new tab\" href=\"../docs/?path=docs/implementation-notes/Servicing/Product/ProdListInq-ImplNotes.md\">click here</a>.</blockquote>"
      operationId: ProductListInqOperByPathSecured
      parameters:
      - name: EFXHeader
        in: header
        description: EFX Header is a common and required component for all API calls, it contains authentication and client-related parameters. Please note that the header parameters should be sent as a JSON object under the EFXHeader parameter. To view the list of header parameters, <a href="../docs?path=docs/api-ref-EFX-header.md" title="Click to open"> click here.</a>
        required: true
        schema:
          $ref: '#/components/schemas/EFXHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductListInqRqType'
            examples:
              Sample Premier:
                $ref: '#/components/examples/ProductListInqRequest-Premier'
              Sample Precision:
                $ref: '#/components/examples/ProductListInqRequest-Precision'
              Sample Signature:
                $ref: '#/components/examples/ProductListInqRequest-Signature'
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListInqRsType'
              examples:
                Sample Premier:
                  $ref: '#/components/examples/ProductListInqResponse-Premier'
                Sample Precision:
                  $ref: '#/components/examples/ProductListInqResponse-Precision'
                Sample Signature:
                  $ref: '#/components/examples/ProductListInqResponse-Signature'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListInqRsType'
              examples:
                "401":
                  $ref: '#/components/examples/401-Premier'
        "422":
          description: Un-processable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListInqRsType'
              examples:
                "422":
                  $ref: '#/components/examples/422-Premier'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListInqRsType'
              examples:
                "500":
                  $ref: '#/components/examples/500-Premier'
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListInqRsType'
              examples:
                "503":
                  $ref: '#/components/examples/503-Premier'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListInqRsType'
      x-group-name: Product Service
      x-proxy-name: Get Product List
      x-child-product-name: ["Core Banking Extended","Operations and Servicing"]
components:
  schemas:
    AcctCategoryType:
      title: AcctCategoryType
      type: string
      example: Deposit
      enum:
      - Loan
      - Deposit
    SubjectElementType:
      title: SubjectElementType
      type: object
      properties:
        Path:
          type: string
          description: Path of the element (in XPath absolute notation format) where the error occurred.  If the error occurred at the top-level element, then name of the element is returned in the response.
        ServerPath:
          maxLength: 256
          type: string
          description: Server Path is the Service Providerâ€™s identification of the field in their schema, such as an XPath, field ID, or field name that is associated with the ServerStatusCode. If this element is set, it must be returned in the ServerPath element of the OvrdExceptionData aggregate if the exception is being overridden.
        Value:
          maxLength: 256
          type: string
          description: Human readable information of the EFX data value of the element to be overridden. This value should not be provided for the fields that cannot be represented as a string, for example, binary data.
      description: Information about the subject element
    RecCtrlInType:
      title: RecCtrlInType
      type: object
      properties:
        MaxRecLimit:
          type: integer
          description: Maximum Record Limit. This is the maximum number of records that the server should add to the result set which is available to satisfy this request.
          format: int64
        Cursor:
          maxLength: 250
          type: string
          description: Cursor. Next Record Pointer Included in the response only if additional records are available.
    ProductListSelType:
      title: ProductListSelType
      type: object
      properties:
        AcctCategory:
          $ref: '#/components/schemas/AcctCategoryType'
        AcctType:
          type: string
          description: Type of an account
        IncNonActiveInd:
          type: boolean
          description: Include Non Active Products.
      description: Selection criteria details to search for required product list
    ProductListInqRqType:
      title: ProductListInqRqType
      required:
      - ProductListSel
      type: object
      properties:
        ProductListSel:
          $ref: '#/components/schemas/ProductListSelType'
    RecCtrlOutType:
      title: RecCtrlOutType
      required:
      - SentRecCount
      type: object
      properties:
        SentRecCount:
          type: integer
          description: Total number of records that matched the selection criteria and returned in the response message
          format: int64
      description: Information retrieved for the criteria specified in the RecCtrlIn aggregate of the request message
    SvcIdentType:
      title: SvcIdentType
      type: object
      properties:
        SvcProviderName:
          maxLength: 1024
          type: string
          description: Service Provider Name is a globally unique identifier for a service provider which indicates the location of the Service Provider that gave the error.
        SvcNbr:
          maxLength: 36
          type: string
          description: Service Number.
        SvcName:
          maxLength: 32
          type: string
          description: Service Name.
    ProductKeysType:
      title: ProductKeysType
      type: object
      properties:
        AcctType:
          type: string
          description: Type of an account
        ProductIdent:
          maxLength: 42
          type: string
          description: Unique identifier of a product record
      description: Unique information to identify a product record
    ProductListInfoType:
      title: ProductListInfoType
      type: object
      properties:
        AcctType:
          type: string
          description: Type of an account
        ProductIdent:
          maxLength: 42
          type: string
          description: Unique identifier of a product
        Desc:
          maxLength: 100
          type: string
          description: Description of the product used to set up the account
        ProductDtlStatus:
          type: string
          description: Details of the current status of the product
        OfferStartDt:
          type: string
          description: 'Start date of the offer <br> Format: yyyy-mm-dd '
          format: date
          example: 2021-11-20
        OfferEndDt:
          type: string
          description: 'End date of the offer <br> Format: yyyy-mm-dd '
          format: date
          example: 2021-11-20
      description: 'Information of the product list '
    ProductStatusCodeType:
      title: ProductStatusCodeType
      type: string
      description: Code to specify product status
      enum:
      - Valid
      - Deleted
    ProductStatusType:
      title: ProductStatusType
      required:
      - ProductStatusCode
      type: object
      properties:
        ProductStatusCode:
          $ref: '#/components/schemas/ProductStatusCodeType'
        EffDt:
          pattern: ^\[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?$
          type: string
          description: 'Effective date and time when the product status is changed. <br> Format: yyyy-MM-ddTHH:mm:ss.SSS'
          example: 2021-01-31T23:59:59.999
      description: Details of the product status
    ProductListRecType:
      title: ProductListRecType
      required:
      - ProductKeys
      - ProductListInfo
      - ProductStatus
      type: object
      properties:
        ProductKeys:
          $ref: '#/components/schemas/ProductKeysType'
        ProductListInfo:
          $ref: '#/components/schemas/ProductListInfoType'
        ProductStatus:
          $ref: '#/components/schemas/ProductStatusType'
      description: Details of the product list record
    ProductListInqRsType:
      title: ProductListInqRsType
      required:
      - Status
      type: object
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        RecCtrlOut:
          $ref: '#/components/schemas/RecCtrlOutType'
        ProductListRec:
          type: array
          description: Details of the product list record
          items:
            $ref: '#/components/schemas/ProductListRecType'
    EFXHeader:
      required:
      - OrganizationId
      type: string
      properties:
        OrganizationId:
          type: string
        TrnId:
          maxLength: 36
          type: string
        VendorId:
          type: string
          description: An identifier, supplied by Fiserv, that represents the vendor using  this API service.
        Context:
          $ref: '#/components/schemas/Context'
      example: '{ "TrnId": "f262cfa4-9da4-4a10-b48c-2e947ce3e66c", "OrganizationId": "PRMOrg10", "VendorId": "112233", "Context":{ "Channel": "WEB" } }'
    Context:
      type: object
      properties:
        ClientAppName:
          maxLength: 40
          type: string
          description: Client Application Name of the application making the service request (e.g. Architect, Commercial Center, etc.).
        Channel:
          type: string
          description: Indicates the channel used by the client application.
        ClientDateTime:
          type: string
          description: Client date and time as reported by the client application that is making the service request.
          format: date-time
        ClientTerminalSeqNum:
          maxLength: 36
          type: string
          description: Also known as Trace Number or Sequence in some systems. Used to allow the client terminal to set a unique identifier for the transaction. When used by a Network defined transaction the value of this identifier is typically set to narrow character of 12.
        OriginatorType:
          type: integer
          description: "\"The type of organization that the originator represents. This is usually a coded value representing the industry that the organization operates in. It contains the SIC code. For ISO 8583 (DE18) the element is restricted to narrow character of maximum length of 4.\nOriginator Type codes that apply to financialinstitutions are:\n  6010 - Financial institutionâ€”bank, savings and loan (S and L), or credit union  \n  6011 - Financial institutionâ€”ATM \n  6012 - Financial institutionâ€”merchandise sale \n  6999 - Financial\ninstitutionâ€”home banking\""
          format: int64
        TerminalIdent:
          maxLength: 36
          type: string
          description: Unique code identifying a terminal at the card acceptor locatio (such as terminal code or terminal number of ATM). See For ISO 8583 (DE41) the element is restricted to a narrow character with maximum length of 8.
        TerminalAddr1:
          maxLength: 64
          type: string
        TerminalAddr2:
          maxLength: 64
          type: string
        TerminalAddr3:
          maxLength: 64
          type: string
        TerminalAddr4:
          maxLength: 64
          type: string
        TerminalCity:
          maxLength: 32
          type: string
        TerminalCounty:
          maxLength: 32
          type: string
        TerminalStateProv:
          maxLength: 32
          type: string
          description: State Province. ISO 3166-2:US codes.
        TerminalPostalCode:
          maxLength: 11
          type: string
          description: Postal Code is ZipCode in the US.
        TerminalCountryCodeSource:
          type: string
          description: Country code source.ISO3166-Numeric, ISO3166-Alpha-3
          enum:
          - ISO3166Numeric
          - ISO3166Alpha3
        TerminalCountryCodeValue:
          maxLength: 80
          type: string
        PhoneType:
          type: string
        PhoneNum:
          type: string
        PhoneExchange:
          type: string
        TerminalOwnerName:
          maxLength: 40
          type: string
          description: Name of the owner or operator of the terminal.  For ISO 8583 (DE43) the element is restricted to C-15.
        SystTraceAuditNum:
          maxLength: 36
          type: string
          description: Number assigned by the transaction originator to assist in identifying a transaction uniquely. The trace number remains unchanged for all messages throughout the life of a transaction. This number is not a terminal receipt number. The originating processor increments the trace number by one for each transaction sent to the switch. For ISO 8583 (DE11) the element is restricted to NC-6
        NetworkIdent:
          maxLength: 80
          type: string
          description: Identifies the interchange network for the transaction. The transaction is applied to the specified network settlement counts and balances. For ISO 8583 (DE62) the element is restricted to NC-6
        NetworkRefIdent:
          maxLength: 36
          type: string
          description: Document reference supplied by the system retaining the original source document and used to assist in locating that document. The acquirer of a transaction assigns this number. The issuer processor must retain it in the event that a chargeback is submitted for the transaction. For ISO 8583 (DE37) the element is restricted to C-12
        AcquirerIdent:
          maxLength: 36
          type: string
          description: Identifies the acquirer of the authorization or financial transaction. It is a mandatory element in all authorization and financial messages and does not change throughout the life of a transaction. EPOC considers the acquirer as the terminal owner for reporting purposes. For ISO 8583 (DE32) the element is restricted to C-12
        AcquirerCountryCodeSource:
          type: string
          description: Country code source.ISO3166-Numeric, ISO3166-Alpha-3
          enum:
          - US
          - IND
        AcquirerCountryCodeValue:
          type: string
        MerchNum:
          maxLength: 23
          type: string
          description: Merchant Number. For ISO 8583 (DE42) the element is restricted to C-15
        SettlementDate:
          type: string
          description: This is the date on which the transaction will be settled. Used by ISO 8583 (DE63)
          format: date
        SettlementIdent:
          maxLength: 36
          type: string
          description: This is the identification of the settlement account in which the transaction will be settled.
        BusinessApplIdent:
          type: string
          description: This is the identification of the settlement account in which the transaction will be settled.
        BranchIdent:
          maxLength: 22
          type: string
        TellerIdent:
          type: string
        TillIdent:
          type: string
        AMPMCode:
          type: string
          enum:
          - AM
          - PM
        ReentryType:
          type: string
          enum:
          - Manual
          - Auto
    StatusType:
      title: StatusType
      required:
      - Severity
      - StatusCode
      - StatusDesc
      - SvcProviderName
      type: object
      properties:
        AdditionalStatus:
          type: array
          description: Details of the additional status of the response message. This aggrigate can appear once for each additional status that the server is expected to provide.
          items:
            $ref: '#/components/schemas/AdditionalStatusType'
        ContentHTML:
          type: string
          description: Response status in HTML format. This parameter returns only in some cases.
        Id:
          type: string
          description: Status identification number.
        OvrdExceptionInd:
          type: boolean
          description: Flag to indicate whether the exception can be overridden by resubmitting the request message.
        ServerStatusCode:
          maxLength: 20
          type: string
          description: Server status code of the service provider's application.
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
        SubjectRole:
          type: string
          description: Authorization level required to override, such as Teller and Supervisor.
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              -  Cleartouch
              -  DNA
              -  Precision
              -  Premier
              -  Signature
      description: Details of the API response messages.
    AdditionalStatusType:
      title: AdditionalStatusType
      type: object
      properties:
        OvrdExceptionInd:
          type: boolean
          description: Flag that indicates whether the exception can be overridden by resubmitting the request message.
        ServerStatusCode:
          maxLength: 20
          type: string
          description: 'Server status code of the service provider''s application.  '
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> for more information.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              - Cleartouch
              - DNA
              - Precision
              - Premier
              - Signature
    SeverityType:
      title: SeverityType
      type: string
      description: Severity type of the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
      enum:
      - Error
      - Warning
      - Info
  examples:
    "401-Premier":
      value:
        Status:
          StatusCode: "1740"
          StatusDesc: Authentication Failed
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "401"
          ServerStatusDesc: Unauthorized
    "422-Premier":
      value:
        Status:
          StatusCode: "1090"
          StatusDesc: Invalid Value
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "422"
          ServerStatusDesc: Unprocessable Entity
    "500-Premier":
      value:
        Status:
          StatusCode: "100"
          StatusDesc: General Error
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "500"
          ServerStatusDesc: Internal Server Error
    "503-Premier":
      value:
        Status:
          StatusCode: "300"
          StatusDesc: System Not Available
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "503"
          ServerStatusDesc: Service Unavailable
    ProductListInqRequest-Premier:
      value:
        ProductListSel:
          AcctType: DDA
    ProductListInqResponse-Premier:
      value:
        Status:
          StatusCode: "0"
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        RecCtrlOut:
          SentRecCount: 6
        ProductListRec:
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "10100"
          ProductListInfo:
            AcctType: DDA
            ProductIdent: "10100"
            Desc: REGULAR
            ProductDtlStatus: Active
            OfferStartDt: 2020-09-24
            OfferEndDt: 2022-12-31
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2022-01-20T16:19:50.335
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "10103"
          ProductListInfo:
            AcctType: DDA
            ProductIdent: "10103"
            Desc: MONEY MARKET
            ProductDtlStatus: Active
            OfferStartDt: 2020-09-24
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2022-01-20T16:19:50.335
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "10105"
          ProductListInfo:
            AcctType: DDA
            ProductIdent: "10105"
            Desc: BUSINESS
            ProductDtlStatus: Active
            OfferStartDt: 2020-09-24
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2022-01-20T16:19:50.336
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "10107"
          ProductListInfo:
            AcctType: DDA
            ProductIdent: "10107"
            Desc: THRIFT
            ProductDtlStatus: Active
            OfferStartDt: 2020-09-24
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2022-01-20T16:19:50.336
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "10115"
          ProductListInfo:
            AcctType: DDA
            ProductIdent: "10115"
            Desc: FIFTY FIVE PLUS
            ProductDtlStatus: Active
            OfferStartDt: 2020-09-24
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2022-01-20T16:19:50.337
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "10199"
          ProductListInfo:
            AcctType: DDA
            ProductIdent: "10199"
            Desc: PUBLIC FUND
            ProductDtlStatus: Active
            OfferStartDt: 2020-09-24
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2022-01-20T16:19:50.434
    ProductListInqRequest-Signature:
      value:
        ProductListSel:
          AcctType: DDA
          IncNonActiveInd: true
    ProductListInqResponse-Signature:
      value:
        Status:
          StatusCode: "0"
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Signature
        RecCtrlOut:
          SentRecCount: "10"
          MatchedRecCount: "99"
          Cursor: "134"
        ProductListRec:
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "110"
          ProductListInfo:
            AcctCategory: Deposit
            AcctType: DDA
            Desc: PERSONAL CKING NON INT BEARING
            AcctUse: Personal
            TaxIncentiveType: None
            ProductDtlStatus: Active
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2019-01-29T02:26:01.826
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "112"
          ProductListInfo:
            AcctCategory: Deposit
            AcctType: DDA
            Desc: STUDENT CHECKING
            AcctUse: Personal
            TaxIncentiveType: None
            ProductDtlStatus: Active
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2019-01-29T02:26:01.826
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "115"
          ProductListInfo:
            AcctCategory: Deposit
            AcctType: DDA
            Desc: VALUE BANKING 55
            AcctUse: Personal
            TaxIncentiveType: None
            ProductDtlStatus: Active
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2019-01-29T02:26:01.827
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "120"
          ProductListInfo:
            AcctCategory: Deposit
            AcctType: DDA
            Desc: COMMERCIAL CHECKING ANALYSIS
            AcctUse: Business
            TaxIncentiveType: None
            ProductDtlStatus: Active
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2019-01-29T02:26:01.827
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "121"
          ProductListInfo:
            AcctCategory: Deposit
            AcctType: DDA
            Desc: BUSINESS CHECKING
            AcctUse: Business
            TaxIncentiveType: None
            ProductDtlStatus: Active
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2019-01-29T02:26:01.827
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "122"
          ProductListInfo:
            AcctCategory: Deposit
            AcctType: DDA
            Desc: COMM CHECKING II
            AcctUse: Business
            TaxIncentiveType: None
            ProductDtlStatus: Active
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2019-01-29T02:26:01.827
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "123"
          ProductListInfo:
            AcctCategory: Deposit
            AcctType: DDA
            Desc: BUS INT BEARING
            AcctUse: Business
            TaxIncentiveType: None
            ProductDtlStatus: Active
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2019-01-29T02:26:01.828
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "125"
          ProductListInfo:
            AcctCategory: Deposit
            AcctType: DDA
            Desc: CBS BANK CHECKS
            AcctUse: Business
            TaxIncentiveType: None
            ProductDtlStatus: Active
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2019-01-29T02:26:01.828
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "130"
          ProductListInfo:
            AcctCategory: Deposit
            AcctType: DDA
            Desc: PUBLIC FUNDS NON INT BEARING
            AcctUse: Business
            TaxIncentiveType: None
            ProductDtlStatus: Active
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2019-01-29T02:26:01.828
        - ProductKeys:
            AcctType: DDA
            ProductIdent: "134"
          ProductListInfo:
            AcctCategory: Deposit
            AcctType: DDA
            Desc: FDIC Shadow Prod-Ext-NOW PerCK
            AcctUse: Personal
            TaxIncentiveType: None
            ProductDtlStatus: Active
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2019-01-29T02:26:01.829
    ProductListInqRequest-Precision:
      value:
        ProductListSel:
          AcctCategory: Deposit
          AcctType: CDA
    ProductListInqResponse-Precision:
      value:
        Status:
          StatusCode: "0"
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Precision
        RecCtrlOut:
          SentRecCount: "16"
        ProductListRec:
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "1"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: Internal Desc J
            OfferEndDt: 2050-12-31
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.726
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "2"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: 182 Day CD
            OfferEndDt: 2050-12-31
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.726
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "3"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: 1 Year CD
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.726
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "4"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: 2 Year CD
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.726
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "5"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: 3 Year CD
            OfferEndDt: 2050-12-31
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.726
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "6"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: 4 Year CD
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.726
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "7"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: '>100M CD'
            OfferEndDt: 2050-12-31
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.726
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "11"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: 91 Day PF CD
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.727
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "12"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: 182 Day PF CD
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.727
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "13"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: 1 Year PF CD
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.727
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "14"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: 2 Year PF CD
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.727
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "15"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: 3 Year PF CD
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.727
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "16"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: 4 Year PF CD
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.727
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "17"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: '>100M PF CD'
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.728
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "19"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: Depository Inst
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.728
        - ProductKeys:
            AcctType: CDA
            ProductIdent: "20"
          ProductListInfo:
            AcctCategory: Deposit
            Desc: Retirement Plan
          ProductStatus:
            ProductStatusCode: Valid
            EffDt: 2020-12-01T14:45:56.728
