---
openapi: 3.0.0
info:
  title: ePreference Service
  description: ePreference service contains methods that allow consumers to set up instructions for electronic document delivery distribution.
  contact:
    name: Monica Sarda
    email: Monica.Sarda@fiserv.com
  version: 11.0.0
servers:
- url: /
paths:
  /ePreferences:
    put:
      tags:
      - Update ePreference
      summary: Update ePreference.
      description: Modifies an existing ePreference record. <br> For more information about the Accounts and Transactions domain, <a href="../docs/?path=docs/fintechs/acct-and-transactions.md" title="Click to open">click here.</a><br><br> <b>Relates to:</b> <ul> <li><a href="../docs/?path=docs/banks-and-CU/deposits.md" title="Click to open">Deposits</a></li> <li><a href="../docs/?path=docs/banks-and-CU/loans.md" title="Click to open">Loans</a></li> <li><a href="../docs/?path=docs/banks-and-CU/bank-servicing.md" title="Click to open">Bank Servicing</a></li> </ul>
      operationId: modifyEPreference
      parameters:
      - name: EFXHeader
        in: header
        description: EFX Header is a common and required component for all API calls, it contains authentication and client-related parameters. Please note that the header parameters should be sent as a JSON object under the EFXHeader parameter. To view the list of header parameters, <a href="../docs?path=docs/api-ref-EFX-header.md" title="Click to open"> click here.</a>
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/EFXHeader'
      requestBody:
        description: Modify Information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EPreferenceModRqType'
            examples:
              Sample Banking:
                $ref: '#/components/examples/ePreferencesModRequest-Premier'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EPreferenceModRsType'
              examples:
                Sample Banking:
                  $ref: '#/components/examples/ePreferencesModResponse-Premier'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                "401":
                  $ref: '#/components/examples/401-Premier'
        "422":
          description: Un-processable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                "422":
                  $ref: '#/components/examples/422-Premier'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                "500":
                  $ref: '#/components/examples/500-Premier'
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                "503":
                  $ref: '#/components/examples/503-Premier'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      deprecated: false
      x-group-name: Document Preferences Service
      x-proxy-name: Update ePreference
      x-child-product-name: Accounts and Transactions
    post:
      tags:
      - Add ePreference
      summary: Add ePreference.
      description: "Adds a new ePreference record. <br> This API creates instructions for electronic document delivery and stops generation of paper statements and notices associated with an account. <br> For more information about the Accounts and Transactions domain, <a href=\"../docs/?path=docs/fintechs/acct-and-transactions.md\" title=\"Click to open\">click here.</a><br><br> <b>Relates to:</b>\n  <ul> \n    <li><a href=\"../docs/?path=docs/banks-and-CU/deposits.md\" title=\"Click to open\">Deposits</a></li>\n    <li><a href=\"../docs/?path=docs/banks-and-CU/loans.md\" title=\"Click to open\">Loans</a></li>\n    <li><a href=\"../docs/?path=docs/banks-and-CU/bank-servicing.md\" title=\"Click to open\">Bank Servicing</a></li>\n  </ul>"
      operationId: addEPreference
      parameters:
      - name: EFXHeader
        in: header
        description: EFX Header is a common and required component for all API calls, it contains authentication and client-related parameters. Please note that the header parameters should be sent as a JSON object under the EFXHeader parameter. To view the list of header parameters, <a href="../docs?path=docs/api-ref-EFX-header.md" title="Click to open"> click here.</a>
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/EFXHeader'
      requestBody:
        description: Add Information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EPreferenceAddRqType'
            examples:
              Sample Banking:
                $ref: '#/components/examples/ePreferencesAddRequest-Premier'
        required: true
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EPreferenceAddRsType'
              examples:
                Sample Banking:
                  $ref: '#/components/examples/ePreferencesAddResponse-Premier'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusType1'
              examples:
                "401":
                  $ref: '#/components/examples/401-Premier'
        "422":
          description: Un-processable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusType1'
              examples:
                "422":
                  $ref: '#/components/examples/422-Premier'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusType1'
              examples:
                "500":
                  $ref: '#/components/examples/500-Premier'
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusType1'
              examples:
                "503":
                  $ref: '#/components/examples/503-Premier'
        default:
          description: See HTTP Status Code Standards
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EPreferenceAddRsType'
      deprecated: false
      x-group-name: Document Preferences Service
      x-proxy-name: Add ePreference
      x-child-product-name: Accounts and Transactions
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        fields:
          type: string
    EFXHeader:
      required:
      - OrganizationId
      type: string
      properties:
        OrganizationId:
          type: string
        TrnId:
          maxLength: 30
          type: string
        VendorId:
          type: string
          description: An identifier, supplied by Fiserv, that represents the vendor using  this API service.
        Context:
          $ref: '#/components/schemas/Context'
      example: '{ "TrnId": "f262cfa4-9da4-4a10-b48c-2e947ce3e66c", "OrganizationId": "PRMOrg10", "VendorId": "112233", "Context":{ "Channel": "WEB" } }'
    Context:
      type: object
      properties:
        ClientAppName:
          maxLength: 40
          type: string
          description: Client Application Name of the application making the service request (e.g. Architect, Commercial Center, etc.).
        Channel:
          type: string
          description: Indicates the channel used by the client application.
        ClientDateTime:
          pattern: ^\[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?$
          type: string
          description: Client date and time as reported by the client application that is making the service request.
          format: date-time
        ClientTerminalSeqNum:
          maxLength: 36
          type: string
          description: Also known as Trace Number or Sequence in some systems. Used to allow the client terminal to set a unique identifier for the transaction. When used by a Network defined transaction the value of this identifier is typically set to narrow character of 12.
        OriginatorType:
          type: integer
          description: The type of organization that the originator represents. This is usually a coded value representing the industry that the organization operates in. It contains the SIC code. For ISO 8583 (DE18) the element is restricted to narrow character of maximum lenght of 4. Originator Type codes that apply to financial institutions are:- • 6010 - Financial institution—bank, savings and loan (S and L), or credit union • 6011 - Financial institution—ATM • 6012 - Financial institution—merchandise sale • 6999 - Financial institution—home banking
          format: int64
        TerminalIdent:
          maxLength: 36
          type: string
          description: Unique code identifying a terminal at the card acceptor locatio (such as terminal code or terminal number of ATM). See For ISO 8583 (DE41) the element is restricted to a narrow character with maximum length of 8.
        TerminalAddr1:
          maxLength: 64
          type: string
        TerminalAddr2:
          maxLength: 64
          type: string
        TerminalAddr3:
          maxLength: 64
          type: string
        TerminalAddr4:
          maxLength: 64
          type: string
        TerminalCity:
          maxLength: 32
          type: string
        TerminalCounty:
          maxLength: 32
          type: string
        TerminalStateProv:
          maxLength: 32
          type: string
          description: State Province. ISO 3166-2:US codes.
        TerminalPostalCode:
          maxLength: 11
          type: string
          description: Postal Code is ZipCode in the US.
        TerminalCountryCodeSource:
          type: string
          description: Country code source.ISO3166-Numeric, ISO3166-Alpha-3
          enum:
          - ISO3166Numeric
          - ISO3166Alpha3
        TerminalCountryCodeValue:
          maxLength: 80
          type: string
        PhoneType:
          type: string
        PhoneNum:
          type: string
        PhoneExchange:
          type: string
        TerminalOwnerName:
          maxLength: 40
          type: string
          description: Name of the owner or operator of the terminal.  For ISO 8583 (DE43) the element is restricted to C-15.
        SystTraceAuditNum:
          maxLength: 36
          type: string
          description: Number assigned by the transaction originator to assist in identifying a transaction uniquely. The trace number remains unchanged for all messages throughout the life of a transaction. This number is not a terminal receipt number. The originating processor increments the trace number by one for each transaction sent to the switch. For ISO 8583 (DE11) the element is restricted to NC-6
        NetworkIdent:
          maxLength: 80
          type: string
          description: Identifies the interchange network for the transaction. The transaction is applied to the specified network settlement counts and balances. For ISO 8583 (DE62) the element is restricted to NC-6
        NetworkRefIdent:
          maxLength: 36
          type: string
          description: Document reference supplied by the system retaining the original source document and used to assist in locating that document. The acquirer of a transaction assigns this number. The issuer processor must retain it in the event that a chargeback is submitted for the transaction. For ISO 8583 (DE37) the element is restricted to C-12
        AcquirerIdent:
          maxLength: 36
          type: string
          description: Identifies the acquirer of the authorization or financial transaction. It is a mandatory element in all authorization and financial messages and does not change throughout the life of a transaction. EPOC considers the acquirer as the terminal owner for reporting purposes. For ISO 8583 (DE32) the element is restricted to C-12
        AcquirerCountryCodeSource:
          type: string
          description: Country code source.ISO3166-Numeric, ISO3166-Alpha-3
          enum:
          - US
          - IND
        AcquirerCountryCodeValue:
          type: string
        MerchNum:
          maxLength: 23
          type: string
          description: Merchant Number. For ISO 8583 (DE42) the element is restricted to C-15
        SettlementDate:
          type: string
          description: This is the date on which the transaction will be settled. Used by ISO 8583 (DE63)
          format: date
        SettlementIdent:
          maxLength: 36
          type: string
          description: This is the identification of the settlement account in which the transaction will be settled.
        BusinessApplIdent:
          type: string
          description: This is the identification of the settlement account in which the transaction will be settled.
        BranchIdent:
          maxLength: 22
          type: string
        TellerIdent:
          type: string
        TillIdent:
          type: string
        AMPMCode:
          type: string
          enum:
          - AM
          - PM
        ReentryType:
          type: string
          enum:
          - Manual
          - Auto
    CurCodeTypeType:
      title: CurCodeTypeType
      type: string
      enum:
      - ISO4217-Alpha
      - ISO4217-Numeric
    EPreferenceStatusCodeType:
      title: EPreferenceStatusCodeType
      type: string
      description: |-
        Status code of the ePreference record. <br> Valid value is:
          - Valid
      enum:
      - Valid
      - Invalid
      - Deleted
    PartyIdentTypeType:
      title: PartyIdentTypeType
      type: string
      enum:
      - TaxIdent
      - IBId
      - Name
      - MemberNum
      - OrgNum
      - PersonNum
    SeverityType:
      title: SeverityType
      type: string
      description: Severity type of the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
      enum:
      - Error
      - Warning
      - Info
    AcctIdentType:
      title: AcctIdentType
      type: object
      properties:
        AcctIdentType:
          type: string
          description: 'Account Identification Type. Valid values include: AcctNum, AliasAcct, PORT, etc.'
        AcctIdentValue:
          maxLength: 36
          type: string
          description: Account Identification Value. Contains the value of the Account Identifier.
    BaseKeysType:
      title: BaseKeysType
      type: string
    SvcIdentType:
      title: SvcIdentType
      type: string
      properties:
        SvcProviderName:
          maxLength: 1024
          type: string
          description: Service Provider Name is a globally unique identifier for a service provider which indicates the location of the Service Provider that gave the error.
        SvcNbr:
          maxLength: 36
          type: string
          description: Service Number.
        SvcName:
          maxLength: 32
          type: string
          description: Service Name.
    CardIdentType:
      title: CardIdentType
      type: object
      properties:
        CardIdentType:
          type: string
          description: 'Card Identification Type. Valid values include: PORT.'
        CardIdentValue:
          maxLength: 36
          type: string
          description: Card Identification Value.
    CardKeysType:
      title: CardKeysType
      allOf:
      - $ref: '#/components/schemas/BaseKeysType'
      - type: object
        properties:
          SvcIdent:
            $ref: '#/components/schemas/SvcIdentType'
          ISOCode:
            maxLength: 80
            type: string
            description: ISO Card Code. Some systems like Precision instead of ISO Number they use a code to refer to the ISO Number of the card.
          CardNum:
            maxLength: 32
            type: string
            description: Card Number. This number does not include the ISO component of the card identification.
          CardId:
            maxLength: 36
            type: string
            description: Card Identifier. Uniquely identifies a card held at a financial institution (this is the card number as it appears on the card).
          CardSeqNum:
            maxLength: 3
            type: string
            description: Card Sequence Number. Typically refers to the member number (if applicable).
          CardIdent:
            $ref: '#/components/schemas/CardIdentType'
    CurCodeType:
      title: CurCodeType
      required:
      - CurCodeValue
      type: object
      properties:
        CurCodeType:
          $ref: '#/components/schemas/CurCodeTypeType'
        CurCodeTypeEnumDesc:
          maxLength: 80
          type: string
          description: Currency Code Type Enumeration Description.
        CurCodeValue:
          maxLength: 80
          type: string
          description: Currency Code Value. Indicates the Currency Code Value within the CurCodeType table specified.
    AcctKeysType:
      title: AcctKeysType
      description: Unique information to identify the account record
      allOf:
      - type: object
        properties:
          AcctId:
            maxLength: 36
            type: string
            description: Unique identification number of an account record
          AcctType:
            type: string
            description: "Type of an account. <br> Some of the valid values are:\n  - CCA\n  - RRA\n  - LEAS\n  - CDA\n  \n<br> For more information on account types, refer to the Account Types section in <a href=\"../docs?path=docs/api-glossary.md\" title=\"Click to open\"> Glossary </a>."
    SubjectElementType:
      title: SubjectElementType
      type: object
      properties:
        Path:
          type: string
          description: Path of the element (in XPath absolute notation format) where the error occurred.  If the error occurred at the top-level element, then name of the element is returned in the response.
        ServerPath:
          maxLength: 256
          type: string
          description: Server Path is the Service Provider’s identification of the field in their schema, such as an XPath, field ID, or field name that is associated with the ServerStatusCode. If this element is set, it must be returned in the ServerPath element of the OvrdExceptionData aggregate if the exception is being overridden.
        Value:
          maxLength: 256
          type: string
          description: Human readable information of the EFX data value of the element to be overridden. This value should not be provided for the fields that cannot be represented as a string, for example, binary data.
      description: Information about the subject element
    AdditionalStatusType:
      title: AdditionalStatusType
      type: object
      properties:
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> for more information.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              - Cleartouch
              - DNA
              - Precision
              - Premier
              - Signature
        ServerStatusCode:
          maxLength: 20
          type: string
          description: 'Server status code of the service provider''s application.  '
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        OvrdExceptionInd:
          type: boolean
          description: Flag that indicates whether the exception can be overridden by resubmitting the request message.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
    LocatorType:
      title: LocatorType
      type: string
    EmailType:
      title: EmailType
      description: Email address details
      allOf:
      - type: object
        properties:
          EmailType:
            type: string
            description: |-
              Type of Email address . <br> Valid values are:
                - Person
                - Business
          EmailAddr:
            maxLength: 254
            type: string
            description: Email address of the account owner
    EmailLinkType:
      title: EmailLinkType
      required:
      - Email
      type: object
      properties:
        Email:
          $ref: '#/components/schemas/EmailType'
    OvrdElementType:
      title: OvrdElementType
      type: object
      description: Information about the elements that corresponds to the override exception code.
      allOf:
      - $ref: '#/components/schemas/SubjectElementType'
      - type: object
    OverrideExceptionType:
      title: OverrideExceptionType
      type: object
      properties:
        SubjectRole:
          type: string
          description: Role of the subject who is overriding the exception.
        SubjectIdent:
          maxLength: 36
          type: string
          description: Subject identification value to identify the subject who is overriding the exception.
        OvrdExceptionCode:
          maxLength: 40
          type: string
          description: Override exception code to be overridden. This can be the ServerStatusCode from the Message Status section.
        OvrdElement:
          $ref: '#/components/schemas/OvrdElementType'
    OvrdExceptionDataType:
      title: OvrdExceptionDataType
      type: object
      properties:
        OverrideException:
          type: array
          description: List of the exceptions that can be overridden.
          items:
            $ref: '#/components/schemas/OverrideExceptionType'
      description: Details of the exceptions that can be manually acknowledged by the client.
    PartyKeysType:
      title: PartyKeysType
      description: Unique information to identify the party record
      allOf:
      - type: object
        properties:
          PartyId:
            maxLength: 36
            type: string
            description: Unique identification number of an party record
    NoticeDataType:
      title: NoticeDataType
      type: object
      properties:
        NoticeType:
          type: string
          description: |-
            Type of account notice. <br> Valid values are:
              - RegularNotice
              - ChargeBack
        NoticeOption:
          type: string
          description: |-
            Account notice option. <br> Valid value is:
              - NoNotice
    EPreferenceInfoType:
      title: EPreferenceInfoType
      type: object
      properties:
        PartyKeys:
          $ref: '#/components/schemas/PartyKeysType'
        AcctKeys:
          $ref: '#/components/schemas/AcctKeysType'
        DocGroupName:
          type: string
          description: "Document group name is a value used when various documents of group are enrolled as a part of this process. <br> Some of the valid values are:\n  - All\n  - Stmt\n  - Notices\n  - Govt\n  "
        Pswd:
          maxLength: 32
          type: string
          description: Verification password of the documents. For example, a password for password-protected PDF document
        StmtPrepCode:
          maxLength: 80
          type: string
          description: Code for statement preparation used for additional ePreference record
        StmtTruncationOption:
          maxLength: 80
          type: string
          description: 'Option for statement truncation for additional ePreference record '
        NoticeData:
          type: array
          description: Details of the account notice processing data
          items:
            $ref: '#/components/schemas/NoticeDataType'
        EmailLink:
          type: array
          description: Email details to link the email address with the unique user defined key
          items:
            $ref: '#/components/schemas/EmailLinkType'
      description: Details of the ePrefrence record used for the customer account e-Distribution prferences
    EPreferenceAddRqType:
      title: EPreferenceAddRqType
      required:
      - EPreferenceInfo
      type: object
      properties:
        OvrdAutoAckInd:
          type: boolean
          description: 'Flag to indicate if the exceptions should be auto-acknowledged by the system. If this value is set to True, then any exception that can be overridden will be automatically acknowledged by the system and exceptions that cannot be overridden will be returned in the Status aggregate of the response message.  '
        OvrdExceptionData:
          $ref: '#/components/schemas/OvrdExceptionDataType'
        EPreferenceInfo:
          $ref: '#/components/schemas/EPreferenceInfoType'
    StatusType:
      title: StatusType
      required:
      - Severity
      - StatusCode
      - StatusDesc
      - SvcProviderName
      type: object
      properties:
        Id:
          type: string
          description: Status identification number.
        StatusCode:
          maxLength: 20
          type: string
          description: EFX Standard Status code that indicates the result of API response. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section to view the list of all possible status codes.
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief information about the EFX status code. Refer to the <a href="../docs?path=docs/response-codes.md">Response Codes</a> section for more information.
        Severity:
          $ref: '#/components/schemas/SeverityType'
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              -  Cleartouch
              -  DNA
              -  Precision
              -  Premier
              -  Signature
        ServerStatusCode:
          maxLength: 20
          type: string
          description: Server status code of the service provider's application.
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        OvrdExceptionInd:
          type: boolean
          description: Flag to indicate whether the exception can be overridden by resubmitting the request message.
        SubjectRole:
          type: string
          description: Authorization level required to override, such as Teller and Supervisor.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: '#/components/schemas/SubjectElementType'
        ContentHTML:
          type: string
          description: Response status in HTML format. This parameter returns only in some cases.
        AdditionalStatus:
          type: array
          description: Details of the additional status of the response message. This aggrigate can appear once for each additional status that the server is expected to provide.
          items:
            $ref: '#/components/schemas/AdditionalStatusType'
      description: Details of the API response messages.
    StatusType1:
      title: Status Type for Error messages
      required:
      - Status
      type: object
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
    EPreferenceKeysType:
      title: EPreferenceKeysType
      required:
      - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: '#/components/schemas/AcctKeysType'
        EPreferenceIdent:
          maxLength: 36
          type: string
          description: Unique identifier of the ePreference record
    EPreferenceStatusType:
      title: EPreferenceStatusType
      required:
      - EPreferenceStatusCode
      type: object
      properties:
        EPreferenceStatusCode:
          $ref: '#/components/schemas/EPreferenceStatusCodeType'
        EffDt:
          pattern: ^\[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?$
          type: string
          description: 'Effective date and time when the status of the ePrefernce record is changed. <br> Format: yyyy-MM-ddTHH:mm:ss.SSS'
          example: 2021-01-31T23:59:59.999
      description: Status of the ePreference record
    EPreferenceStatusRecType:
      title: EPreferenceStatusRecType
      required:
      - EPreferenceKeys
      - EPreferenceStatus
      type: object
      properties:
        EPreferenceKeys:
          type: array
          description: Unique information to identify the ePreference record
          items:
            $ref: '#/components/schemas/EPreferenceKeysType'
        EPreferenceStatus:
          $ref: '#/components/schemas/EPreferenceStatusType'
      description: Details of the updated status of the ePreference record
    EPreferenceAddRsType:
      title: EPreferenceAddRsType
      required:
      - Status
      type: object
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        EPreferenceStatusRec:
          $ref: '#/components/schemas/EPreferenceStatusRecType'
    EPreferenceDelRqType:
      title: EPreferenceDelRqType
      required:
      - EPreferenceKeys
      type: object
      properties:
        OvrdAutoAckInd:
          type: boolean
          description: Override AutoAcknowledge Indicator. Used when the midleware is in charge of  auto-acknowledgement of exceptions.
        OvrdExceptionData:
          $ref: '#/components/schemas/OvrdExceptionDataType'
        EPreferenceKeys:
          $ref: '#/components/schemas/EPreferenceKeysType'
    EPreferenceDelRsType:
      title: EPreferenceDelRsType
      required:
      - Status
      type: object
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        EPreferenceStatusRec:
          $ref: '#/components/schemas/EPreferenceStatusRecType'
    RecCtrlInType:
      title: RecCtrlInType
      type: object
      properties:
        MaxRecLimit:
          type: integer
          description: Maximum Record Limit. This is the maximum number of records that the server should add to the result set which is available to satisfy this request.
          format: int64
        Cursor:
          maxLength: 250
          type: string
          description: Cursor. Next Record Pointer Included in the response only if additional records are available.
    EPreferenceSelType:
      title: EPreferenceSelType
      type: object
      properties:
        EPreferenceKeys:
          $ref: '#/components/schemas/EPreferenceKeysType'
        AcctKeys:
          $ref: '#/components/schemas/AcctKeysType'
    EPreferenceInqRqType:
      title: EPreferenceInqRqType
      required:
      - EPreferenceSel
      type: object
      properties:
        RecCtrlIn:
          $ref: '#/components/schemas/RecCtrlInType'
        EPreferenceSel:
          $ref: '#/components/schemas/EPreferenceSelType'
    RecCtrlOutType:
      title: RecCtrlOutType
      required:
      - SentRecCount
      type: object
      properties:
        SentRecCount:
          type: integer
          description: Sent Record Count. Number of records matching the selection criteria that are included in this message.
          format: int64
        MatchedRecCount:
          type: integer
          description: Matched Record Count. Total number of records matching the selection criteria.
          format: int64
        RemainRecCount:
          type: integer
          description: Remain Record Count.  Total number of records matching the selection criteria that have not been sent yet.
          format: int64
        Cursor:
          maxLength: 250
          type: string
          description: Cursor. Next Record Pointer Included in the response only if additional records are available.
    EPreferenceRecType:
      title: EPreferenceRecType
      required:
      - EPreferenceInfo
      - EPreferenceKeys
      - EPreferenceStatus
      type: object
      properties:
        EPreferenceKeys:
          $ref: '#/components/schemas/EPreferenceKeysType'
        EPreferenceInfo:
          $ref: '#/components/schemas/EPreferenceInfoType'
        EPreferenceStatus:
          $ref: '#/components/schemas/EPreferenceStatusType'
      description: '[FSVR]e-Preference Record.'
    EPreferenceInqRsType:
      title: EPreferenceInqRsType
      required:
      - Status
      type: object
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        RecCtrlOut:
          $ref: '#/components/schemas/RecCtrlOutType'
        EPreferenceRec:
          type: array
          description: e-Preference Record.
          items:
            $ref: '#/components/schemas/EPreferenceRecType'
    EPreferenceModRqType:
      title: EPreferenceModRqType
      required:
      - EPreferenceInfo
      - EPreferenceKeys
      type: object
      properties:
        OvrdAutoAckInd:
          type: boolean
          description: 'Flag to indicate if the exceptions should be auto-acknowledged by the system. If this value is set to True, then any exception that can be overridden will be automatically acknowledged by the system and exceptions that cannot be overridden will be returned in the Status aggregate of the response message.  '
        OvrdExceptionData:
          $ref: '#/components/schemas/OvrdExceptionDataType'
        EPreferenceKeys:
          $ref: '#/components/schemas/EPreferenceKeysType'
        EPreferenceInfo:
          $ref: '#/components/schemas/EPreferenceInfoType'
    EPreferenceModRsType:
      title: EPreferenceModRsType
      required:
      - Status
      type: object
      properties:
        Status:
          $ref: '#/components/schemas/StatusType'
        EPreferenceStatusRec:
          $ref: '#/components/schemas/EPreferenceStatusRecType'
  examples:
    "401-Premier":
      value:
        Status:
          StatusCode: "1740"
          StatusDesc: Authentication Failed
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "401"
          ServerStatusDesc: Unauthorized
    "422-Premier":
      value:
        Status:
          StatusCode: "1090"
          StatusDesc: Invalid Value
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "422"
          ServerStatusDesc: Unprocessable Entity
    "500-Premier":
      value:
        Status:
          StatusCode: "100"
          StatusDesc: General Error
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "500"
          ServerStatusDesc: Internal Server Error
    "503-Premier":
      value:
        Status:
          StatusCode: "300"
          StatusDesc: System Not Available
          Severity: Error
          SvcProviderName: Premier
          ServerStatusCode: "503"
          ServerStatusDesc: Service Unavailable
    ePreferencesAddRequest-Premier:
      value:
        EPreferenceInfo:
          PartyKeys:
            PartyId: "3140"
          AcctKeys:
            AcctId: "200183"
            AcctType: DDA
          DocGroupName: "2"
          Pswd: "123"
          StmtPrepCode: "1"
          StmtTruncationOption: "1"
          NoticeData:
          - NoticeType: RegularNotice
            NoticeOption: "1"
          EmailLink:
          - Email:
              EmailType: Business
              EmailAddr: DDA_9999.X@gmail.com
    ePreferencesAddResponse-Premier:
      value:
        Status:
          StatusCode: "0"
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        EPreferenceStatusRec:
          EPreferenceKeys:
          - AcctKeys:
              AcctId: "200183"
              AcctType: DDA
            EPreferenceIdent: "1"
          EPreferenceStatus:
            EPreferenceStatusCode: Valid
            EffDt: 2022-01-17T11:38:19.041
    ePreferencesModRequest-Premier:
      value:
        EPreferenceKeys:
          AcctKeys:
            AcctId: "200183"
            AcctType: DDA
          EPreferenceIdent: "2"
        EPreferenceInfo:
          DocGroupName: "2"
          Pswd: "123"
          StmtPrepCode: No Statement
          StmtTruncationOption: "0"
          NoticeData:
          - NoticeType: RegularNotice
            NoticeOption: "1"
          - NoticeType: ChargeBack
          EmailLink:
          - Email:
              EmailType: Business
              EmailAddr: 9xddaMod@gmail.com
              PreferredEmail: "true"
            UserKey: "521"
    ePreferencesModResponse-Premier:
      value:
        Status:
          StatusCode: "0"
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        EPreferenceStatusRec:
          EPreferenceKeys:
          - AcctKeys:
              AcctId: "200183"
            EPreferenceIdent: "2"
          EPreferenceStatus:
            EPreferenceStatusCode: Valid
            EffDt: 2022-01-17T11:44:57.195
    ePreferencesInqRequest-Premier:
      value:
        EPreferenceSel:
          AcctKeys:
            AcctId: "1270"
            AcctType: SDA
    ePreferencesInqResponse-Premier:
      value:
        Status:
          StatusCode: "0"
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        RecCtrlOut:
          SentRecCount: 1
        EPreferenceRec:
        - EPreferenceKeys:
            AcctKeys:
              AcctId: "1270"
              AcctType: SDA
            EPreferenceIdent: "0"
          EPreferenceInfo:
            DocGroupName: "2"
            CombinedStmtInd: true
            Pswd: "0"
            EmailLink:
            - Email:
                EmailType: Business
                EmailAddr: DEEPAK.GARG@FISERV.COM
                PreferredEmail: false
              UserKey: "241"
          EPreferenceStatus:
            EPreferenceStatusCode: Valid
            EffDt: 2021-11-22T17:00:17.148
    ePreferencesDelRequest-Premier:
      value:
        EPreferenceKeys:
          AcctKeys:
            AcctId: "200183"
            AcctType: DDA
          ePreferenceIdent: 1
    ePreferencesDelResponse-Premier:
      value:
        Status:
          StatusCode: 0
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Premier
        ePreferenceStatusRec:
          ePreferenceKeys:
            AcctKeys:
              AcctId: "200183"
              AcctType: DDA
            ePreferenceIdent: 1
          ePreferenceStatus:
            ePreferenceStatusCode: Valid
            EffDt: 2021-11-29T12:10:00.904
